#!/bin/bash

list="$(find html -type f -printf "%p \\\\\n" | sed 's/^/\t/')"
echo "dist_html_DATA = \\
${list/%\\/}" > Makefile.am

list="$(find man -type f -printf "%p \\\\\n" | sed 's/^/\t/')"
echo "dist_man_MANS = \\
${list/%\\/}" >> Makefile.am
