.TH "ConvInt< Char_T, T >" 3 "Wed Nov 16 2016" "Version 10.28.07" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConvInt< Char_T, T > \- Contains a function to convert integer to string (either \fCstd::string\fP or \fCstd::wstring\fP ( or \fCstd::u16string\fP or \fCstd::u32string\fP for >=C++11)  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename Char_T, typename T = Char_T>
.br
struct ConvInt< Char_T, T >"
Contains a function to convert integer to string (either \fCstd::string\fP or \fCstd::wstring\fP ( or \fCstd::u16string\fP or \fCstd::u32string\fP for >=C++11) 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fIChar_T\fP Basic character type (\fCchar\fP, \fCwchar\fP, \fCchar16_t\fP, \fCchar32_t\fP)\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
