.TH "ConvUTF< Char_T >" 3 "Wed Nov 16 2016" "Version 10.28.07" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConvUTF< Char_T > \- \fCUTF-8 <> UTF-16\fP and \fCUTF-8 <> UTF32\fP converter (\fC>=C++11\fP)\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename Char_T>
.br
struct ConvUTF< Char_T >"
\fCUTF-8 <> UTF-16\fP and \fCUTF-8 <> UTF32\fP converter (\fC>=C++11\fP)\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
