.TH "deprecated" 3 "Tue Mar 7 2017" "Version 10.29.03" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecatedDeprecated List 
 \- 
.IP "\fBMember \fBjpcre2::select< Char_T, BS >::Regex::getMatchObject\fP ()\fP" 1c
Returns a reference to existing match object\&. 
.IP "\fBMember \fBjpcre2::select< Char_T, BS >::Regex::getReplaceObject\fP ()\fP" 1c
Returns a reference to the existing \fBRegexReplace\fP object\&. 
.IP "\fBMember \fBjpcre2::select< Char_T, BS >::Regex::initMatch\fP ()\fP" 1c
.IP "\fBMember \fBjpcre2::select< Char_T, BS >::Regex::initMatchFrom\fP (const \fBRegexMatch\fP &rmo)\fP" 1c
Copy the match object into this \fBRegex\fP object\&. 
.IP "\fBMember \fBjpcre2::select< Char_T, BS >::Regex::initReplace\fP ()\fP" 1c
.IP "\fBMember \fBjpcre2::select< Char_T, BS >::Regex::initReplaceFrom\fP (const \fBRegexReplace\fP &rro)\fP" 1c
Copy the replace object into this \fBRegex\fP object\&. 
.IP "\fBMember \fBjpcre2::select< Char_T, BS >::Regex::match\fP ()\fP" 1c
Shorthand for \fBgetMatchObject()\fP\&.\fBmatch()\fP This uses previously initiated match object i\&.e call \fBRegexMatch::match()\fP with all previous options intact\&. 
.IP "\fBMember \fBjpcre2::select< Char_T, BS >::Regex::replace\fP ()\fP" 1c
.PP

