.TH "jpcre2::Codecvt< internT, externT, stateT >" 3 "Sun Sep 25 2016" "Version 10.27.02" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::Codecvt< internT, externT, stateT > \- Convenience wrapper of \fCstd::codecvt\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jpcre2\&.hpp>\fP
.SH "Detailed Description"
.PP 

.SS "template<class internT, class externT, class stateT>
.br
struct jpcre2::Codecvt< internT, externT, stateT >"
Convenience wrapper of \fCstd::codecvt\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
