jpcre2::select8< Char_T >::RegexMatch
NAME
jpcre2::select8< Char_T >::RegexMatch - Provides the RegexMatch::match() function to perform regex matching.
SYNOPSIS
Public Member Functions
RegexMatch & reset ()
Reset all class variables to its default (initial) state.
String getSubject ()
Get subject string.
std::string getModifier ()
Calculate modifier string from PCRE2 and JPCRE2 options and return it.
Uint getPcre2Option ()
Get PCRE2 option.
Uint getJpcre2Option ()
Get JPCRE2 option.
RegexMatch & resetErrors ()
Reset errors to zero.
RegexMatch & setNumberedSubstringVector (VecNum *v)
Set a pointer to the numbered substring vector.
RegexMatch & setNamedSubstringVector (VecNas *v)
Set a pointer to the named substring vector.
RegexMatch & setNameToNumberMapVector (VecNtN *v)
Set a pointer to the name to number map vector.
RegexMatch & setSubject (const String &s)
Set the subject string for match.
RegexMatch & setModifier (const std::string &s)
Set the modifier (overwrites existing JPCRE2 and PCRE2 option).
RegexMatch & setJpcre2Option (Uint x)
Set JPCRE2 option for match (overwrite existing option)
RegexMatch & setPcre2Option (Uint x)
Set PCRE2 option match (overwrite existing option)
RegexMatch & setFindAll (bool x)
Set whether to perform global match.
RegexMatch & setFindAll ()
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function just calls RegexMatch::setFindAll(bool x) with true as the parameter. "
RegexMatch & changeModifier (const std::string &, bool)
After a call to this function PCRE2 and JPCRE2 options will be properly set.
RegexMatch & changeJpcre2Option (Uint opt, bool x)
Parse modifier and add/remove equivalent PCRE2 and JPCRE2 options.
RegexMatch & changePcre2Option (Uint opt, bool x)
Add or remove a PCRE2 option.
RegexMatch & addModifier (const std::string &mod)
Parse modifier string and add equivalent PCRE2 and JPCRE2 options.
RegexMatch & addJpcre2Option (Uint x)
Add option to existing JPCRE2 options for match.
RegexMatch & addPcre2Option (Uint x)
Add option to existing PCRE2 options for match.
SIZE_T match (void)
Perfor match operaton using info from class variables and return the match count.
Detailed Description
template<class Char_T>
class jpcre2::select8< Char_T >::RegexMatch"
Provides the RegexMatch::match() function to perform regex matching.
Provides chained methods to set various options.
All constructors of this class are private.
Member Function Documentation
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::addJpcre2Option (Uint x) [inline]
Add option to existing JPCRE2 options for match.
Parameters:
x Option value
Returns:
Reference to the calling RegexMatch object
See also:
RegexReplace::addJpcre2Option()
Regex::addJpcre2Option()
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::addModifier (const std::string & mod) [inline]
Parse modifier string and add equivalent PCRE2 and JPCRE2 options. This is just a wrapper of the original function RegexMatch::changeModifier() provided for convenience.
Note: If speed of operation is very crucial, use RegexMatch::addJpcre2Option() and RegexMatch::addPcre2Option() with equivalent options. It will be faster that way.
Parameters:
mod Modifier string
Returns:
Reference to the calling RegexMatch object
See also:
RegexReplace::addModifier()
Regex::addModifier()
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::addPcre2Option (Uint x) [inline]
Add option to existing PCRE2 options for match.
Parameters:
x Option value
Returns:
Reference to the calling RegexMatch object
See also:
RegexReplace::addPcre2Option()
Regex::addPcre2Option()
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::changeJpcre2Option (Uint opt, bool x) [inline]
Parse modifier and add/remove equivalent PCRE2 and JPCRE2 options. Add or remove a JPCRE2 option
Parameters:
opt JPCRE2 option value
x Add the option if it's true, remove otherwise.
Returns:
Reference to the calling RegexMatch object
See also:
RegexReplace::changeJpcre2Option()
Regex::changeJpcre2Option()
template<class Char_T > jpcre2::select8< Char_T >::RegexMatch::changeModifier (const std::string & mod, bool x)
After a call to this function PCRE2 and JPCRE2 options will be properly set. This function does not initialize or re-initialize options. If you want to set options from scratch, initialize them to 0 before calling this function.
Note: If speed of operation is very crucial, use RegexMatch::changeJpcre2Option() and RegexMatch::changePcre2Option() with equivalent options. It will be faster that way.
If JPCRE2_ASSERT_INVALID_MODIFIER macro is defined, invalid modifier will give you runtime error and yield to immediate termination of the program.
Template Parameters:
Char_T Character type
Parameters:
mod Modifier string
x Whether to add or remove option
Returns:
Reference to the RegexMatch object
See also:
jpcre2::select8<Char_T>::Regex::changeModifier()
jpcre2::select8<Char_T>::RegexReplace::changeModifier()
References jpcre2::select8< Char_T >::Regex::changeJpcre2Option(), jpcre2::select8< Char_T >::Regex::changePcre2Option(), jpcre2::MOD::M_N, jpcre2::MOD::M_V, jpcre2::MOD::MJ_N, jpcre2::MOD::MJ_V, and jpcre2::select8< Char_T >::toString().
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::changePcre2Option (Uint opt, bool x) [inline]
Add or remove a PCRE2 option.
Parameters:
opt PCRE2 option value
x Add the option if it's true, remove otherwise.
Returns:
Reference to the calling RegexMatch object
See also:
RegexReplace::changePcre2Option()
Regex::changePcre2Option()
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::getJpcre2Option () [inline]
Get JPCRE2 option.
Returns:
JPCRE2 options for math operation
See also:
jpcre2::select8<Char_T>::Regex::getJpcre2Option()
jpcre2::select8<Char_T>::RegexReplace::getJpcre2Option()
template<class Char_T > jpcre2::select8< Char_T >::RegexMatch::getModifier ()
Calculate modifier string from PCRE2 and JPCRE2 options and return it. Do remember that modifiers (or PCRE2 and JPCRE2 options) do not change or get initialized as long as you don't do that explicitly. Calling RegexMatch::setModifier() will re-set them.
Mixed or combined modifier.
Some modifier may include other modifiers i.e they have the same meaning of some modifiers combined together. For example, the 'n' modifier includes the 'u' modifier and together they are equivalent to PCRE2_UTF | PCRE2_UCP. When you set a modifier like this, both options get set, and when you remove the 'n' modifier RegexMatch::changeModifier(), both will get removed
Template Parameters:
Char_T Character type
Returns:
Calculated modifier string (std::string)
See also:
jpcre2::select8<Char_T>::Regex::getModifier()
jpcre2::select8<Char_T>::RegexMatchReplace::getModifier()
References jpcre2::MOD::M_N, jpcre2::MOD::M_V, jpcre2::MOD::MJ_N, and jpcre2::MOD::MJ_V.
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::getPcre2Option () [inline]
Get PCRE2 option.
Returns:
PCRE2 option for match operation
See also:
jpcre2::select8<Char_T>::Regex::getPcre2Option()
jpcre2::select8<Char_T>::RegexReplace::getPcre2Option()
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::getSubject () [inline]
Get subject string.
Returns:
subject string
See also:
jpcre2::select8<Char_T>::RegexReplace::getSubject()
template<class Char_T > jpcre2::select8< Char_T >::RegexMatch::match (void)
Perfor match operaton using info from class variables and return the match count.
Returns:
Match count
References jpcre2::FIND_ALL.
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::reset () [inline]
Reset all class variables to its default (initial) state. Data in the vectors will retain. You will need to pass vector pointers again after calling this function to get match results.
Returns:
Reference to the calling RegexMatch object.
template<class Char_T > jpcre2::select8< Char_T >::RegexMatch::resetErrors ()
Reset errors to zero. If you want to examine the error status of a function call in the method chain, add this function just before your target function so that the error is set to zero before that target function is called, and leave everything out after the target function so that there will be no additional errors from other function calls.
This function is callable from everywhere in a method chain, i.e other copy of this function for other classes are available and they do the exactly same thing.
Template Parameters:
Char_T Character type.
Returns:
A reference to the RegexMatch object
See also:
jpcre2::select8<Char_T>::Regex::resetErrors()
jpcre2::select8<Char_T>::RegexReplace::resetErrors()
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::setFindAll () [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function just calls RegexMatch::setFindAll(bool x) with true as the parameter.
Returns:
Reference to the calling RegexMatch object
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::setFindAll (bool x) [inline]
Set whether to perform global match.
Parameters:
x True or False
Returns:
Reference to the calling RegexMatch object
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::setJpcre2Option (Uint x) [inline]
Set JPCRE2 option for match (overwrite existing option)
Parameters:
x Option value
Returns:
Reference to the calling RegexMatch object
See also:
jpcre2::select8<Char_T>::RegexReplace::setJpcre2Option()
jpcre2::select8<Char_T>::Regex::setJpcre2Option()
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::setModifier (const std::string & s) [inline]
Set the modifier (overwrites existing JPCRE2 and PCRE2 option). Re-initializes the option bits for PCRE2 and JPCRE2 options, then parses the modifier to set their equivalent options.
Note: If speed of operation is very crucial, use RegexMatch::setJpcre2Option() and RegexMatch::setPcre2Option() with equivalent options. It will be faster that way.
Parameters:
s Modifier string
Returns:
Reference to the calling RegexMatch object
See also:
jpcre2::select8<Char_T>::RegexReplace::setModifier()
jpcre2::select8<Char_T>::Regex::setModifier()
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::setNamedSubstringVector (VecNas * v) [inline]
Set a pointer to the named substring vector. This vector will be populated with named captured groups.
Parameters:
v pointer to the named substring vector
Returns:
Reference to the calling RegexMatch object
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::setNameToNumberMapVector (VecNtN * v) [inline]
Set a pointer to the name to number map vector. This vector will be populated with name to number map for captured groups.
Parameters:
v pointer to the name to number map vector
Returns:
Reference to the calling RegexMatch object
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::setNumberedSubstringVector (VecNum * v) [inline]
Set a pointer to the numbered substring vector. This vector will be filled with numbered (indexed) captured groups.
Parameters:
v pointer to the numbered substring vector
Returns:
Reference to the calling RegexMatch object
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::setPcre2Option (Uint x) [inline]
Set PCRE2 option match (overwrite existing option)
Parameters:
x Option value
Returns:
Reference to the calling RegexMatch object
See also:
jpcre2::select8<Char_T>::RegexReplace::setPcre2Option()
jpcre2::select8<Char_T>::Regex::setPcre2Option()
template<class Char_T> jpcre2::select8< Char_T >::RegexMatch::setSubject (const String & s) [inline]
Set the subject string for match.
Parameters:
s Subject string
Returns:
Reference to the calling RegexMatch object
See also:
jpcre2::select8<Char_T>::RegexReplace::setSubject()
Author
Generated automatically by Doxygen for JPCRE2 from the source code.