.TH "jpcre2::ConvInt< Char_T, T >" 3 "Fri Nov 18 2016" "Version 10.28.08" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::ConvInt< Char_T, T > \- Contains a function to convert integer to string\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jpcre2\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::basic_string< Char_T > \fBtoString\fP (int x)"
.br
.RI "Converts an integer to string\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Char_T, typename T = Char_T>
.br
struct jpcre2::ConvInt< Char_T, T >"
Contains a function to convert integer to string\&. 

Integer is converted to \fCstd::basic_string<Char_T>\fP 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIChar_T\fP Basic character type (\fCchar\fP, \fCwchar\fP, \fCchar16_t\fP, \fCchar32_t\fP)\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename Char_T , typename T  = Char_T> std::basic_string<Char_T> \fBjpcre2::ConvInt\fP< Char_T, T >::toString (int x)"

.PP
Converts an integer to string\&. String may be \fCstd::string\fP, \fCstd::wstring\fP (\fCstd::u16string\fP, \fCstd::u32string\fP if \fC>=C++11\fP) 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP the integer to convert 
.RE
.PP
\fBReturns:\fP
.RS 4
\fCstd::string\fP/\fCstd::wstring\fP/\fCstd::u16string\fP/\fCstd::u32string\fP from the integer 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
