.TH "jpcre2::MSG< Char_T >" 3 "Mon Oct 31 2016" "Version 10.28.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::MSG< Char_T > \- JPCRE2 messages as \fBjpcre2::select::String\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jpcre2\&.hpp>\fP
.SH "Detailed Description"
.PP 

.SS "template<typename Char_T>
.br
struct jpcre2::MSG< Char_T >"
JPCRE2 messages as \fBjpcre2::select::String\fP\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
