jpcre2::select< Char_T, Map >::Regex
NAME
jpcre2::select< Char_T, Map >::Regex - Provides public constructors to create Regex object.
SYNOPSIS
#include <jpcre2.hpp>
Public Member Functions
Regex ()
Default Constructor.
Regex (String const &re)
Compile pattern with initialization.
Regex (String const *re)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Regex (String const &re, Modifier const &mod)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Regex (String const *re, Modifier const &mod)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Regex (String const &re, Uint po)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Regex (String const *re, Uint po)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Regex (String const &re, Uint po, Uint jo)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Regex (String const *re, Uint po, Uint jo)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Regex (Regex const &r)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
Regex & operator= (Regex const &r)
Overloaded assignment operator.
Regex (Regex &&r)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
Regex & operator= (Regex &&r)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
operator bool () const
Provides boolean check for the status of the object.
bool operator! () const
Provides boolean check for the status of the object.
Regex & reset ()
Reset all class variables to its default (initial) state including memory.
Regex & clear ()
Clear all class variables to its default (initial) state (some memory may retain for further use).
Regex & resetErrors ()
Reset regex compile related errors to zero.
Regex & resetCharacterTables ()
Recreate character tables used by PCRE2.
Pcre2Code const * getPcre2Code () const
Get Pcre2 raw compiled code pointer.
String getPattern () const
Get pattern string.
const String * getPatternPointer () const
Get pointer to pattern string.
std::string getModifier () const
Calculate modifier string from PCRE2 and JPCRE2 options and return it.
Uint getPcre2Option () const
Get PCRE2 option.
Uint getJpcre2Option () const
Get JPCRE2 option.
int getErrorNumber () const
Returns the last error number.
int getErrorOffset () const
Returns the last error offset.
String getErrorMessage () const
Returns the last error message.
Uint getNewLine ()
Get new line convention from compiled code.
ModifierTable const * getModifierTable ()
Get the modifier table that is set,.
Regex & setNewLine (Uint value)
Set new line convention.
Regex & setPattern (String const &re)
Set the pattern string to compile.
Regex & setPattern (String const *re)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Regex & setModifier (Modifier const &x)
set the modifier (resets all JPCRE2 and PCRE2 options) by calling Regex::changeModifier().
Regex & setModifierTable (ModifierTable const *mdt)
Set a custom modifier table to be used.
Regex & setJpcre2Option (Uint x)
Set JPCRE2 option for compile (overwrites existing option)
Regex & setPcre2Option (Uint x)
Set PCRE2 option for compile (overwrites existing option)
Regex & changeModifier (Modifier const &mod, bool x)
Parse modifier and add/remove equivalent PCRE2 and JPCRE2 options.
Regex & changeJpcre2Option (Uint opt, bool x)
Add or remove a JPCRE2 option.
Regex & changePcre2Option (Uint opt, bool x)
Add or remove a PCRE2 option.
Regex & addModifier (Modifier const &mod)
Parse modifier string and add equivalent PCRE2 and JPCRE2 options.
Regex & addJpcre2Option (Uint x)
Add option to existing JPCRE2 options for compile.
Regex & addPcre2Option (Uint x)
Add option to existing PCRE2 options for compile.
void compile (void)
Compile pattern using info from class variables.
void compile (String const &re, Uint po, Uint jo)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
void compile (String const *re, Uint po, Uint jo)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void compile (String const &re, Uint po)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void compile (String const *re, Uint po)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void compile (String const &re, Modifier const &mod)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void compile (String const *re, Modifier const &mod)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void compile (String const &re)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void compile (String const *re)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
RegexMatch initMatch ()
Returns a default constructed RegexMatch object by value.
RegexMatch getMatchObject ()
Synonym for initMatch()
SIZE_T match (String const &s, Modifier const &mod, PCRE2_SIZE start_offset=0)
Perform regex match and return match count using a temporary match object.
SIZE_T match (String const *s, Modifier const &mod, PCRE2_SIZE start_offset=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
SIZE_T match (String const &s, PCRE2_SIZE start_offset=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
SIZE_T match (String const *s, PCRE2_SIZE start_offset=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
RegexReplace initReplace ()
Returns a default constructed RegexReplace object by value.
RegexReplace getReplaceObject ()
Synonym for initReplace()
String replace (String const &mains, String const &repl, Modifier const &mod='', SIZE_T *counter=0)
Perform regex replace and return the replaced string using a temporary replace object.
String replace (String *mains, String const &repl, Modifier const &mod='', SIZE_T *counter=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
String replace (String const &mains, String const *repl, Modifier const &mod='', SIZE_T *counter=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
String replace (String *mains, String const *repl, Modifier const &mod='', SIZE_T *counter=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
SIZE_T preplace (String *mains, String const &repl, Modifier const &mod='')
Perl compatible replace method.
SIZE_T preplace (String *mains, String const *repl, Modifier const &mod='')
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Perl compatible replace method. "
SIZE_T preplace (String const &mains, String const &repl, Modifier const &mod='')
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Perl compatible replace method. "
SIZE_T preplace (String const &mains, String const *repl, Modifier const &mod='')
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Perl compatible replace method. "
Detailed Description
template<typename Char_T, template< typename... > class Map = std::map>
class jpcre2::select< Char_T, Map >::Regex"
Provides public constructors to create Regex object.
Each regex pattern needs an object of this class and each pattern needs to be compiled. Pattern compilation can be done using one of its' overloaded constructors or the Regex::compile() member function.
Examples:
jp::Regex re; //does not perform a compile
re.compile("pattern", "modifier");
jp::Regex re2("pattern", "modifier"); //performs a compile
Constructor & Destructor Documentation
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::Regex::Regex () [inline]
Default Constructor. Initializes all class variables to defaults. Does not perform any pattern compilation.
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::Regex::Regex (String const & re) [inline]
Compile pattern with initialization.
Parameters
re Pattern string
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::Regex::Regex (String const * re) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pointer to pattern string. A null pointer will unset the pattern and perform a compile with empty pattern.
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::Regex::Regex (String const & re, Modifier const & mod) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pattern string .
mod Modifier string.
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::Regex::Regex (String const * re, Modifier const & mod) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pointer to pattern string. A null pointer will unset the pattern and perform a compile with empty pattern.
mod Modifier string.
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::Regex::Regex (String const & re, Uint po) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pattern string .
po PCRE2 option value
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::Regex::Regex (String const * re, Uint po) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pointer to pattern string. A null pointer will unset the pattern and perform a compile with empty pattern.
po PCRE2 option value
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::Regex::Regex (String const & re, Uint po, Uint jo) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pattern string .
po PCRE2 option value
jo JPCRE2 option value
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::Regex::Regex (String const * re, Uint po, Uint jo) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pointer to pattern string. A null pointer will unset the pattern and perform a compile with empty pattern.
po PCRE2 option value
jo JPCRE2 option value
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::Regex::Regex (Regex const & r) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Copy constructor. A separate and new compile is performed from the copied options.
Parameters
r Constant Regex object reference.
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::Regex::Regex (Regex && r) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Move constructor. This constructor steals resources from the argument. It leaves the argument in a valid but indeterminate sate. The indeterminate state can be returned to normal by calling reset() on that object.
Parameters
r rvalue reference to a Regex object.
Member Function Documentation
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::addJpcre2Option (Uint x) [inline]
Add option to existing JPCRE2 options for compile.
Parameters
x Option value
Returns
Reference to the calling Regex object
See also
RegexMatch::addJpcre2Option()
RegexReplace::addJpcre2Option()
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::addModifier (Modifier const & mod) [inline]
Parse modifier string and add equivalent PCRE2 and JPCRE2 options. This is just a wrapper of the original function Regex::changeModifier() provided for convenience.
Parameters
mod Modifier string.
Returns
Reference to the calling Regex object
See also
RegexMatch::addModifier()
RegexReplace::addModifier()
References jpcre2::select< Char_T, Map >::Regex::changeModifier().
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::addPcre2Option (Uint x) [inline]
Add option to existing PCRE2 options for compile.
Parameters
x Option value
Returns
Reference to the calling Regex object
See also
RegexMatch::addPcre2Option()
RegexReplace::addPcre2Option()
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::changeJpcre2Option (Uint opt, bool x) [inline]
Add or remove a JPCRE2 option.
Parameters
opt JPCRE2 option value
x Add the option if it's true, remove otherwise.
Returns
Reference to the calling Regex object
See also
RegexMatch::changeJpcre2Option()
RegexReplace::changeJpcre2Option()
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::changeModifier (Modifier const & mod, bool x) [inline]
Parse modifier and add/remove equivalent PCRE2 and JPCRE2 options. This function does not initialize or re-initialize options. If you want to set options from scratch, initialize them to 0 before calling this function.
If invalid modifier is detected, then the error number for the Regex object will be jpcre2::ERROR::INVALID_MODIFIER and error offset will be the modifier character. You can get the message with Regex::getErrorMessage() function.
Parameters
mod Modifier string.
x Whether to add or remove option
Returns
Reference to the calling Regex object
See also
RegexMatch::changeModifier()
RegexReplace::changeModifier()
References jpcre2::ModifierTable::toCompileOption().
Referenced by jpcre2::select< Char_T, Map >::Regex::addModifier(), and jpcre2::select< Char_T, Map >::Regex::setModifier().
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::changePcre2Option (Uint opt, bool x) [inline]
Add or remove a PCRE2 option.
Parameters
opt PCRE2 option value
x Add the option if it's true, remove otherwise.
Returns
Reference to the calling Regex object
See also
RegexMatch::changePcre2Option()
RegexReplace::changePcre2Option()
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::clear () [inline]
Clear all class variables to its default (initial) state (some memory may retain for further use).
Returns
Reference to the calling Regex object.
template<typename Char_T , template< typename... > class Map = std::map> void jpcre2::select< Char_T, Map >::Regex::compile (String const & re) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pattern string .
template<typename Char_T , template< typename... > class Map = std::map> void jpcre2::select< Char_T, Map >::Regex::compile (String const & re, Modifier const & mod) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pattern string
mod Modifier string.
template<typename Char_T , template< typename... > class Map = std::map> void jpcre2::select< Char_T, Map >::Regex::compile (String const & re, Uint po) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pattern string
po PCRE2 option
template<typename Char_T , template< typename... > class Map = std::map> void jpcre2::select< Char_T, Map >::Regex::compile (String const & re, Uint po, Uint jo) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Set the specified parameters, then compile the pattern using information from class variables.
Parameters
re Pattern string
po PCRE2 option
jo JPCRE2 option
template<typename Char_T , template< typename... > class Map = std::map> void jpcre2::select< Char_T, Map >::Regex::compile (String const * re) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pointer to pattern string. A null pointer will unset the pattern and perform a compile with empty pattern.
template<typename Char_T , template< typename... > class Map = std::map> void jpcre2::select< Char_T, Map >::Regex::compile (String const * re, Modifier const & mod) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pointer to pattern string. A null pointer will unset the pattern and perform a compile with empty pattern.
mod Modifier string.
template<typename Char_T , template< typename... > class Map = std::map> void jpcre2::select< Char_T, Map >::Regex::compile (String const * re, Uint po) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pointer to pattern string. A null pointer will unset the pattern and perform a compile with empty pattern.
po PCRE2 option
template<typename Char_T , template< typename... > class Map = std::map> void jpcre2::select< Char_T, Map >::Regex::compile (String const * re, Uint po, Uint jo) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pointer to pattern string. A null pointer will unset the pattern and perform a compile with empty pattern.
po PCRE2 option
jo JPCRE2 option
template<typename Char_T , template< typename... > class Map> void jpcre2::select< Char_T, Map >::Regex::compile (void)
Compile pattern using info from class variables.
See also
Regex::compile(String const &re, Uint po, Uint jo)
Regex::compile(String const &re, Uint po)
Regex::compile(String const &re, Modifier mod)
Regex::compile(String const &re)
References jpcre2::JIT_COMPILE.
template<typename Char_T , template< typename... > class Map = std::map> String jpcre2::select< Char_T, Map >::Regex::getErrorMessage () const [inline]
Returns the last error message.
Returns
Last error message
References jpcre2::select< Char_T, Map >::getErrorMessage().
template<typename Char_T , template< typename... > class Map = std::map> int jpcre2::select< Char_T, Map >::Regex::getErrorNumber () const [inline]
Returns the last error number.
Returns
Last error number
template<typename Char_T , template< typename... > class Map = std::map> int jpcre2::select< Char_T, Map >::Regex::getErrorOffset () const [inline]
Returns the last error offset.
Returns
Last error offset
template<typename Char_T , template< typename... > class Map = std::map> Uint jpcre2::select< Char_T, Map >::Regex::getJpcre2Option () const [inline]
Get JPCRE2 option.
Returns
Compile time JPCRE2 option value
See also
RegexReplace::getJpcre2Option()
RegexMatch::getJpcre2Option()
template<typename Char_T , template< typename... > class Map = std::map> RegexMatch jpcre2::select< Char_T, Map >::Regex::getMatchObject () [inline]
Synonym for initMatch()
Returns
RegexMatch object by value.
References jpcre2::select< Char_T, Map >::Regex::initMatch().
template<typename Char_T , template< typename... > class Map = std::map> std::string jpcre2::select< Char_T, Map >::Regex::getModifier () const [inline]
Calculate modifier string from PCRE2 and JPCRE2 options and return it. Mixed or combined modifier.
Some modifier may include other modifiers i.e they have the same meaning of some modifiers combined together. For example, the 'n' modifier includes the 'u' modifier and together they are equivalent to PCRE2_UTF | PCRE2_UCP. When you set a modifier like this, both options get set, and when you remove the 'n' modifier (with Regex::changeModifier()), both will get removed.
Template Parameters
Char_T Character type
Returns
Calculated modifier string (std::string)
See also
RegexMatch::getModifier()
RegexReplace::getModifier()
References jpcre2::ModifierTable::fromCompileOption().
template<typename Char_T , template< typename... > class Map = std::map> ModifierTable const* jpcre2::select< Char_T, Map >::Regex::getModifierTable () [inline]
Get the modifier table that is set,.
Returns
constant ModifierTable pointer.
template<typename Char_T , template< typename... > class Map = std::map> Uint jpcre2::select< Char_T, Map >::Regex::getNewLine () [inline]
Get new line convention from compiled code.
Returns
New line option value or 0.
PCRE2_NEWLINE_CR Carriage return only
PCRE2_NEWLINE_LF Linefeed only
PCRE2_NEWLINE_CRLF CR followed by LF only
PCRE2_NEWLINE_ANYCRLF Any of the above
PCRE2_NEWLINE_ANY Any Unicode newline sequence
template<typename Char_T , template< typename... > class Map = std::map> String jpcre2::select< Char_T, Map >::Regex::getPattern () const [inline]
Get pattern string.
Returns
pattern string of type jpcre2::select::String
template<typename Char_T , template< typename... > class Map = std::map> const String* jpcre2::select< Char_T, Map >::Regex::getPatternPointer () const [inline]
Get pointer to pattern string.
Returns
Pointer to constant pattern string
template<typename Char_T , template< typename... > class Map = std::map> Pcre2Code const* jpcre2::select< Char_T, Map >::Regex::getPcre2Code () const [inline]
Get Pcre2 raw compiled code pointer.
Returns
pointer to constant pcre2_code or null.
template<typename Char_T , template< typename... > class Map = std::map> Uint jpcre2::select< Char_T, Map >::Regex::getPcre2Option () const [inline]
Get PCRE2 option.
Returns
Compile time PCRE2 option value
See also
RegexReplace::getPcre2Option()
RegexMatch::getPcre2Option()
template<typename Char_T , template< typename... > class Map = std::map> RegexReplace jpcre2::select< Char_T, Map >::Regex::getReplaceObject () [inline]
Synonym for initReplace()
Returns
RegexReplace object.
References jpcre2::select< Char_T, Map >::Regex::initReplace().
template<typename Char_T , template< typename... > class Map = std::map> RegexMatch jpcre2::select< Char_T, Map >::Regex::initMatch () [inline]
Returns a default constructed RegexMatch object by value. This object is initialized with the same modifier table as this Regex object.
Returns
RegexMatch object.
Referenced by jpcre2::select< Char_T, Map >::Regex::getMatchObject().
template<typename Char_T , template< typename... > class Map = std::map> RegexReplace jpcre2::select< Char_T, Map >::Regex::initReplace () [inline]
Returns a default constructed RegexReplace object by value. This object is initialized with the same modifier table as this Regex object.
Returns
RegexReplace object.
Referenced by jpcre2::select< Char_T, Map >::Regex::getReplaceObject(), jpcre2::select< Char_T, Map >::Regex::preplace(), and jpcre2::select< Char_T, Map >::Regex::replace().
template<typename Char_T , template< typename... > class Map = std::map> SIZE_T jpcre2::select< Char_T, Map >::Regex::match (String const & s, Modifier const & mod, PCRE2_SIZE start_offset = 0) [inline]
Perform regex match and return match count using a temporary match object. This temporary match object will get available options from this Regex object, that includes modifier table.
Parameters
s Subject string .
mod Modifier string.
start_offset Offset from where matching will start in the subject string.
Returns
Match count
See also
RegexMatch::match()
template<typename Char_T , template< typename... > class Map = std::map> SIZE_T jpcre2::select< Char_T, Map >::Regex::match (String const & s, PCRE2_SIZE start_offset = 0) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
Parameters
s Subject string .
start_offset Offset from where matching will start in the subject string.
Returns
Match count
See also
RegexMatch::match()
template<typename Char_T , template< typename... > class Map = std::map> SIZE_T jpcre2::select< Char_T, Map >::Regex::match (String const * s, Modifier const & mod, PCRE2_SIZE start_offset = 0) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
Parameters
s Pointer to subject string. A null pointer will unset the subject and perform a match with empty subject.
mod Modifier string.
start_offset Offset from where matching will start in the subject string.
Returns
Match count
template<typename Char_T , template< typename... > class Map = std::map> SIZE_T jpcre2::select< Char_T, Map >::Regex::match (String const * s, PCRE2_SIZE start_offset = 0) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
Parameters
s Pointer to subject string. A null pointer will unset the subject and perform a match with empty subject.
start_offset Offset from where matching will start in the subject string.
Returns
Match count
See also
RegexMatch::match()
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::Regex::operator bool () const [inline], [explicit]
Provides boolean check for the status of the object. This overloaded boolean operator needs to be declared explicit to prevent implicit conversion and overloading issues.
We will only enable it if >=C++11 is being used, as the explicit keyword for a function other than constructor is not supported in older compilers.
If you are dealing with legacy code/compilers use the Double bang trick mentioned in Regex::operator!().
This helps us to check the status of the compiled regex like this:
jpcre2::select<char>::Regex re("pat", "mod");
if(re) {
    std::cout<<"Compile success";
} else {
    std::cout<<"Compile failed";
}
Returns
true if regex compiled successfully, false otherwise.
template<typename Char_T , template< typename... > class Map = std::map> bool jpcre2::select< Char_T, Map >::Regex::operator! () const [inline]
Provides boolean check for the status of the object. This is a safe boolean approach (no implicit conversion or overloading). We don't need the explicit keyword here and thus it's the preferable method to check for object status that will work well with older compilers. e.g:
jpcre2::select<char>::Regex re("pat","mod");
if(!re) {
    std::cout<<"Compile failed";
} else {
    std::cout<<"Compiled successfully";
}
Double bang trick:
jpcre2::select<char>::Regex re("pat","mod");
if(!!re) {
    std::cout<<"Compiled successfully";
} else {
    std::cout<<"Compile failed";
}
Returns
true if regex compile failed, false otherwise.
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::operator= (Regex && r) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Overloaded move-assignment operator. This constructor steals resources from the argument. It leaves the argument in a valid but indeterminate sate. The indeterminate state can be returned to normal by calling reset() on that object.
Parameters
r Regex&&
Returns
*this
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::operator= (Regex const & r) [inline]
Overloaded assignment operator.
Parameters
r Regex const &
Returns
*this
template<typename Char_T , template< typename... > class Map = std::map> SIZE_T jpcre2::select< Char_T, Map >::Regex::preplace (String * mains, String const & repl, Modifier const & mod = '') [inline]
Perl compatible replace method. Modifies subject string in-place and returns replace count.
It's a shorthand method to RegexReplace::preplace().
Parameters
mains Pointer to subject string.
repl Replacement string (string to replace with).
mod Modifier string.
Returns
replace count.
References jpcre2::select< Char_T, Map >::Regex::initReplace(), jpcre2::select< Char_T, Map >::RegexReplace::replace(), jpcre2::select< Char_T, Map >::RegexReplace::setModifier(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceCounter(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceWith(), and jpcre2::select< Char_T, Map >::RegexReplace::setSubject().
template<typename Char_T , template< typename... > class Map = std::map> SIZE_T jpcre2::select< Char_T, Map >::Regex::preplace (String * mains, String const * repl, Modifier const & mod = '') [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Perl compatible replace method. Modifies subject string in-place and returns replace count.
It's a shorthand method to RegexReplace::preplace().
Parameters
mains Pointer to subject string.
repl Pointer to replacement string (string to replace with).
mod Modifier string.
Returns
replace count.
References jpcre2::select< Char_T, Map >::Regex::initReplace(), jpcre2::select< Char_T, Map >::RegexReplace::replace(), jpcre2::select< Char_T, Map >::RegexReplace::setModifier(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceCounter(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceWith(), and jpcre2::select< Char_T, Map >::RegexReplace::setSubject().
template<typename Char_T , template< typename... > class Map = std::map> SIZE_T jpcre2::select< Char_T, Map >::Regex::preplace (String const & mains, String const & repl, Modifier const & mod = '') [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Perl compatible replace method. Returns replace count and discards subject string.
It's a shorthand method to RegexReplace::preplace().
Parameters
mains Subject string.
repl Replacement string (string to replace with).
mod Modifier string.
Returns
replace count.
References jpcre2::select< Char_T, Map >::Regex::initReplace(), jpcre2::select< Char_T, Map >::RegexReplace::replace(), jpcre2::select< Char_T, Map >::RegexReplace::setModifier(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceCounter(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceWith(), and jpcre2::select< Char_T, Map >::RegexReplace::setSubject().
template<typename Char_T , template< typename... > class Map = std::map> SIZE_T jpcre2::select< Char_T, Map >::Regex::preplace (String const & mains, String const * repl, Modifier const & mod = '') [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Perl compatible replace method. Returns replace count and discards subject string.
It's a shorthand method to RegexReplace::preplace().
Parameters
mains Subject string.
repl Pointer to replacement string (string to replace with).
mod Modifier string.
Returns
replace count.
References jpcre2::select< Char_T, Map >::Regex::initReplace(), jpcre2::select< Char_T, Map >::RegexReplace::replace(), jpcre2::select< Char_T, Map >::RegexReplace::setModifier(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceCounter(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceWith(), and jpcre2::select< Char_T, Map >::RegexReplace::setSubject().
template<typename Char_T , template< typename... > class Map = std::map> String jpcre2::select< Char_T, Map >::Regex::replace (String * mains, String const & repl, Modifier const & mod = '', SIZE_T * counter = 0) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
mains Pointer to subject string
repl String to replace with
mod Modifier string.
counter Pointer to a counter to store the number of replacement done.
Returns
Resultant string after regex replace
See also
RegexReplace::replace()
References jpcre2::select< Char_T, Map >::Regex::initReplace(), jpcre2::select< Char_T, Map >::RegexReplace::replace(), jpcre2::select< Char_T, Map >::RegexReplace::setModifier(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceCounter(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceWith(), and jpcre2::select< Char_T, Map >::RegexReplace::setSubject().
template<typename Char_T , template< typename... > class Map = std::map> String jpcre2::select< Char_T, Map >::Regex::replace (String * mains, String const * repl, Modifier const & mod = '', SIZE_T * counter = 0) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
Parameters
mains Pointer to subject string
repl Pointer to string to replace with
mod Modifier string.
counter Pointer to a counter to store the number of replacement done.
Returns
Resultant string after regex replace
See also
RegexReplace::replace()
References jpcre2::select< Char_T, Map >::Regex::initReplace(), jpcre2::select< Char_T, Map >::RegexReplace::replace(), jpcre2::select< Char_T, Map >::RegexReplace::setModifier(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceCounter(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceWith(), and jpcre2::select< Char_T, Map >::RegexReplace::setSubject().
template<typename Char_T , template< typename... > class Map = std::map> String jpcre2::select< Char_T, Map >::Regex::replace (String const & mains, String const & repl, Modifier const & mod = '', SIZE_T * counter = 0) [inline]
Perform regex replace and return the replaced string using a temporary replace object. This temporary replace object will get available options from this Regex object, that includes modifier table.
Parameters
mains Subject string.
repl String to replace with
mod Modifier string.
counter Pointer to a counter to store the number of replacement done.
Returns
Resultant string after regex replace
See also
RegexReplace::replace()
References jpcre2::select< Char_T, Map >::Regex::initReplace(), jpcre2::select< Char_T, Map >::RegexReplace::replace(), jpcre2::select< Char_T, Map >::RegexReplace::setModifier(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceCounter(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceWith(), and jpcre2::select< Char_T, Map >::RegexReplace::setSubject().
template<typename Char_T , template< typename... > class Map = std::map> String jpcre2::select< Char_T, Map >::Regex::replace (String const & mains, String const * repl, Modifier const & mod = '', SIZE_T * counter = 0) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
Parameters
mains Subject string
repl Pointer to string to replace with
mod Modifier string.
counter Pointer to a counter to store the number of replacement done.
Returns
Resultant string after regex replace
See also
RegexReplace::replace()
References jpcre2::select< Char_T, Map >::Regex::initReplace(), jpcre2::select< Char_T, Map >::RegexReplace::replace(), jpcre2::select< Char_T, Map >::RegexReplace::setModifier(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceCounter(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceWith(), and jpcre2::select< Char_T, Map >::RegexReplace::setSubject().
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::reset () [inline]
Reset all class variables to its default (initial) state including memory.
Returns
Reference to the calling Regex object.
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::resetCharacterTables () [inline]
Recreate character tables used by PCRE2. You should call this function after changing the locale to remake the character tables according to the new locale. These character tables are used to compile the regex and used by match and replace operation. A separate call to compile() will be required to apply the new character tables.
Returns
Reference to the calling Regex object.
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::resetErrors () [inline]
Reset regex compile related errors to zero.
Returns
A reference to the Regex object
See also
RegexReplace::resetErrors()
RegexMatch::resetErrors()
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::setJpcre2Option (Uint x) [inline]
Set JPCRE2 option for compile (overwrites existing option)
Parameters
x Option value
Returns
Reference to the calling Regex object.
See also
RegexMatch::setJpcre2Option()
RegexReplace::setJpcre2Option()
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::setModifier (Modifier const & x) [inline]
set the modifier (resets all JPCRE2 and PCRE2 options) by calling Regex::changeModifier(). Re-initializes the option bits for PCRE2 and JPCRE2 options, then parses the modifier and sets equivalent PCRE2 and JPCRE2 options.
Parameters
x Modifier string.
Returns
Reference to the calling Regex object.
See also
RegexMatch::setModifier()
RegexReplace::setModifier()
References jpcre2::select< Char_T, Map >::Regex::changeModifier().
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::setModifierTable (ModifierTable const * mdt) [inline]
Set a custom modifier table to be used.
Parameters
mdt pointer to ModifierTable object.
Returns
Reference to the calling Regex object.
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::setNewLine (Uint value) [inline]
Set new line convention.
Parameters
value New line option value.
PCRE2_NEWLINE_CR Carriage return only
PCRE2_NEWLINE_LF Linefeed only
PCRE2_NEWLINE_CRLF CR followed by LF only
PCRE2_NEWLINE_ANYCRLF Any of the above
PCRE2_NEWLINE_ANY Any Unicode newline sequence
Returns
Reference to the calling Regex object
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::setPattern (String const & re) [inline]
Set the pattern string to compile.
Parameters
re Pattern string
Returns
Reference to the calling Regex object.
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::setPattern (String const * re) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
re Pattern string pointer, null pointer will unset it.
Returns
Reference to the calling Regex object.
template<typename Char_T , template< typename... > class Map = std::map> Regex& jpcre2::select< Char_T, Map >::Regex::setPcre2Option (Uint x) [inline]
Set PCRE2 option for compile (overwrites existing option)
Parameters
x Option value
Returns
Reference to the calling Regex object.
See also
RegexMatch::setPcre2Option()
RegexReplace::setPcre2Option()
Author
Generated automatically by Doxygen for JPCRE2 from the source code.