.TH "jpcre2.hpp" 3 "Fri Jul 21 2017" "Version 10.30.02" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2.hpp \- Main header file for JPCRE2 library to be included by programs that uses its functionalities\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <pcre2\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cwchar>\fP
.br
\fC#include <climits>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <locale>\fP
.br
\fC#include <functional>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjpcre2::Modifier\fP"
.br
.RI "Class to take a std::string modifier value with null safety\&. "
.ti -1c
.RI "class \fBjpcre2::ModifierTable\fP"
.br
.RI "Lets you create custom modifier tables\&. "
.ti -1c
.RI "struct \fBjpcre2::ConvUTF< Char_T >\fP"
.br
.ti -1c
.RI "struct \fBjpcre2::ConvInt< Char_T, T >\fP"
.br
.ti -1c
.RI "struct \fBjpcre2::select< Char_T, BS >\fP"
.br
.RI "struct to select code unit width and the character type\&. "
.ti -1c
.RI "class \fBjpcre2::select< Char_T, BS >::RegexMatch\fP"
.br
.RI "Provides public constructors to create \fBRegexMatch\fP objects\&. "
.ti -1c
.RI "struct \fBjpcre2::select< Char_T, BS >::MatchEvaluatorCallback< T1, T2, T3 >\fP"
.br
.RI "This class contains a typedef of a function pointer or a templated function wrapper (\fCstd::function\fP) to provide callback function to the \fC\fBMatchEvaluator\fP\fP\&. "
.ti -1c
.RI "struct \fBjpcre2::select< Char_T, BS >::callback\fP"
.br
.RI "Provides some default static callback functions\&. "
.ti -1c
.RI "class \fBjpcre2::select< Char_T, BS >::MatchEvaluator\fP"
.br
.RI "This class inherits \fBRegexMatch\fP and provides a similar functionality\&. "
.ti -1c
.RI "class \fBjpcre2::select< Char_T, BS >::RegexReplace\fP"
.br
.RI "Provides public constructors to create \fBRegexReplace\fP objects\&. "
.ti -1c
.RI "class \fBjpcre2::select< Char_T, BS >::Regex\fP"
.br
.RI "Provides public constructors to create \fBRegex\fP object\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjpcre2\fP"
.br
.RI "Top level namespace of JPCRE2\&. "
.ti -1c
.RI " \fBjpcre2::INFO\fP"
.br
.RI "Namespace to provide information about JPCRE2 library itself\&. "
.ti -1c
.RI " \fBjpcre2::ERROR\fP"
.br
.RI "Namespace for error codes\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPCRE2_CODE_UNIT_WIDTH\fP   0"
.br
.RI "This macro does not have any significance in JPCRE2 context\&. "
.ti -1c
.RI "#define \fBJPCRE2_ASSERT\fP(cond,  msg)   \fBjpcre2::jassert\fP(cond, msg, __FILE__, __LINE__)"
.br
.RI "Macro to call \fC\fBjpcre2::jassert()\fP\fP with file path and line number\&. "
.ti -1c
.RI "#define \fBJPCRE2_VERSION\fP   103002L"
.br
.RI "Define for JPCRE2 version\&. "
.ti -1c
.RI "#define \fBJPCRE2_DISABLE_CHAR1632\fP"
.br
.ti -1c
.RI "#define \fBJPCRE2_USE_FUNCTION_POINTER_CALLBACK\fP"
.br
.RI "Use function pointer in all cases for MatchEvaluatorCallback function\&. "
.ti -1c
.RI "#define \fBJPCRE2_DISABLE_CODE_UNIT_WIDTH_VALIDATION\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef PCRE2_SIZE \fBjpcre2::SIZE_T\fP"
.br
.RI "Used for match count and vector size\&. "
.ti -1c
.RI "typedef uint32_t \fBjpcre2::Uint\fP"
.br
.RI "Used for options (bitwise operation) "
.ti -1c
.RI "typedef uint8_t \fBjpcre2::Ush\fP"
.br
.RI "8 bit unsigned integer\&. "
.ti -1c
.RI "typedef std::vector< SIZE_T > \fBjpcre2::VecOff\fP"
.br
.RI "vector of size_t\&. "
.ti -1c
.RI "typedef std::vector< Uint > \fBjpcre2::VecOpt\fP"
.br
.RI "vector for Uint option values\&. "
.ti -1c
.RI "typedef ConvUTF< char16_t >::Converter \fBjpcre2::Convert16\fP"
.br
.ti -1c
.RI "typedef ConvUTF< char32_t >::Converter \fBjpcre2::Convert32\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBjpcre2::ERROR::INVALID_MODIFIER\fP = 2, \fBjpcre2::ERROR::INSUFFICIENT_OVECTOR\fP = 3 }
.RI "Error numbers for JPCRE2\&. ""
.br
.ti -1c
.RI "enum { \fBjpcre2::NONE\fP = 0x0000000u, \fBjpcre2::FIND_ALL\fP = 0x0000002u, \fBjpcre2::JIT_COMPILE\fP = 0x0000004u }
.RI "These constants provide JPCRE2 options\&. ""
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBjpcre2::jassert\fP (bool cond, const char *msg, const char *f, size_t line)"
.br
.RI "JPCRE2 assert function\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const char \fBjpcre2::INFO::NAME\fP [] = 'JPCRE2'"
.br
.RI "Name of the project\&. "
.ti -1c
.RI "static const char \fBjpcre2::INFO::FULL_VERSION\fP [] = '10\&.30\&.02'"
.br
.RI "Full version string\&. "
.ti -1c
.RI "static const char \fBjpcre2::INFO::VERSION_GENRE\fP [] = '10'"
.br
.RI "Generation, depends on original PCRE2 version\&. "
.ti -1c
.RI "static const char \fBjpcre2::INFO::VERSION_MAJOR\fP [] = '30'"
.br
.RI "Major version, updated when API change is made\&. "
.ti -1c
.RI "static const char \fBjpcre2::INFO::VERSION_MINOR\fP [] = '02'"
.br
.RI "Minor version, includes bug fix or minor feature upgrade\&. "
.ti -1c
.RI "static const char \fBjpcre2::INFO::VERSION_PRE_RELEASE\fP [] = ''"
.br
.RI "Alpha or beta (testing) release version\&. "
.in -1c
.SH "Detailed Description"
.PP 
Main header file for JPCRE2 library to be included by programs that uses its functionalities\&. 

It includes the \fCpcre2\&.h\fP header, therefore you shouldn't include \fCpcre2\&.h\fP, neither should you define \fCPCRE2_CODE_UNIT_WIDTH\fP before including \fC\fBjpcre2\&.hpp\fP\fP\&. If your \fCpcre2\&.h\fP header is not in standard include paths, you may include \fCpcre2\&.h\fP with correct path before including \fC\fBjpcre2\&.hpp\fP\fP manually\&. In this case you will have to define \fCPCRE2_CODE_UNIT_WIDTH\fP before including \fCpcre2\&.h\fP\&. Make sure to link required PCRE2 libraries when compiling\&.
.PP
\fBAuthor:\fP
.RS 4
\fCMd Jahidul Hamid\fP 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define JPCRE2_ASSERT(cond, msg)   \fBjpcre2::jassert\fP(cond, msg, __FILE__, __LINE__)"

.PP
Macro to call \fC\fBjpcre2::jassert()\fP\fP with file path and line number\&. When NDEBUG is defined before including this header, this macro will be defined as \fC((void)0)\fP thus eliminating this assertion\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcond\fP condtion (boolean) 
.br
\fImsg\fP message 
.RE
.PP

.PP
Referenced by jpcre2::select< Char_T, BS >::Regex::replace()\&.
.SS "#define JPCRE2_DISABLE_CHAR1632"

.PP
\fBDeprecated\fP
.RS 4
Disable support for \fCchar16_t\fP and \fCchar32_t\fP\&.
.RE
.PP
Older compiler which supposedly supports C++11 but does not have \fCstd::wstring_convert\fP will not work with \fCchar16_t\fP and \fCchar32_t\fP, in this case define this macro before including \fC\fBjpcre2\&.hpp\fP\fP to disable \fCchar16_t\fP and \fCchar32_t\fP support\&. 
.SS "#define JPCRE2_DISABLE_CODE_UNIT_WIDTH_VALIDATION"

.PP
\fBDeprecated\fP
.RS 4
By default JPCRE2 checks if the code unit width equals to sizeof(Char_T)*CHAR_BIT, if not,it will produce compile error\&.
.RE
.PP
This check can be disabled by defining this macro\&. 
.SS "#define JPCRE2_USE_FUNCTION_POINTER_CALLBACK"

.PP
Use function pointer in all cases for MatchEvaluatorCallback function\&. By default function pointer is used for callback in MatchEvaluator when using <C++11 compiler, but for \fC>=C++11\fP compiler \fCstd::function\fP instead of function pointer is used\&. If this macro is defined before including \fBjpcre2\&.hpp\fP, function pointer will be used in all cases\&. It you are using lambda function with captures, stick with \fCstd::function\fP, on the other hand, if you are using older compilers, you might want to use function pointer instead\&.
.PP
For example, with gcc-4\&.7, \fCstd::function\fP will give compile error in C++11 mode, in such cases where full C++11 support is not available, use function pointer\&. 
.SS "#define JPCRE2_VERSION   103002L"

.PP
Define for JPCRE2 version\&. It can be used to support changes in different versions of the lib\&. 
.SS "#define PCRE2_CODE_UNIT_WIDTH   0"

.PP
This macro does not have any significance in JPCRE2 context\&. It is defined as 0 by default\&. Defining it before including \fBjpcre2\&.hpp\fP will override the default (discouraged as it will make it harder for you to detect problems), but still it will have no effect in a JPCRE2 perspective\&. Defining it with an invalid value will yield to compile error\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
