.TH "jpcre2" 3 "Thu Aug 20 2020" "Version 10.32.01" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBERROR\fP"
.br
.ti -1c
.RI " \fBINFO\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBModifier\fP"
.br
.RI "Class to take a std::string modifier value with null safety\&. "
.ti -1c
.RI "class \fBModifierTable\fP"
.br
.RI "Lets you create custom modifier tables\&. "
.ti -1c
.RI "struct \fBselect\fP"
.br
.RI "struct to select the types\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef PCRE2_SIZE \fBSIZE_T\fP"
.br
.RI "Used for match count and vector size\&. "
.ti -1c
.RI "typedef uint32_t \fBUint\fP"
.br
.RI "Used for options (bitwise operation) "
.ti -1c
.RI "typedef uint8_t \fBUsh\fP"
.br
.RI "8 bit unsigned integer\&. "
.ti -1c
.RI "typedef std::vector< \fBSIZE_T\fP > \fBVecOff\fP"
.br
.RI "vector of size_t\&. "
.ti -1c
.RI "typedef std::vector< \fBUint\fP > \fBVecOpt\fP"
.br
.RI "vector for Uint option values\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBNONE\fP = 0x0000000u, \fBFIND_ALL\fP = 0x0000002u, \fBJIT_COMPILE\fP = 0x0000004u }"
.br
.RI "These constants provide JPCRE2 options\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBjassert\fP (bool cond, const char *msg, const char *f, size_t line)"
.br
.RI "JPCRE2 assert function\&. "
.in -1c
.SH "Detailed Description"
.PP 
Top level namespace of JPCRE2\&.
.PP
All functions, classes/structs, constants, enums that are provided by JPCRE2 belong to this namespace while \fBPCRE2\fP structs, functions, constants remain outside of its scope\&.
.PP
If you want to use any PCRE2 functions or constants, remember that they are in the global scope and should be used as such\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef PCRE2_SIZE \fBjpcre2::SIZE_T\fP"

.PP
Used for match count and vector size\&. 
.SS "typedef uint32_t \fBjpcre2::Uint\fP"

.PP
Used for options (bitwise operation) 
.SS "typedef uint8_t \fBjpcre2::Ush\fP"

.PP
8 bit unsigned integer\&. 
.SS "typedef std::vector<\fBSIZE_T\fP> \fBjpcre2::VecOff\fP"

.PP
vector of size_t\&. 
.SS "typedef std::vector<\fBUint\fP> \fBjpcre2::VecOpt\fP"

.PP
vector for Uint option values\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
These constants provide JPCRE2 options\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINONE \fP\fP
Option 0 (zero) 
.TP
\fB\fIFIND_ALL \fP\fP
Find all during match (global match) 
.TP
\fB\fIJIT_COMPILE \fP\fP
Perform JIT compilation for optimization\&. 
.SH "Function Documentation"
.PP 
.SS "static void jpcre2::jassert (bool cond, const char * msg, const char * f, size_t line)\fC [inline]\fP, \fC [static]\fP"

.PP
JPCRE2 assert function\&. Aborts with an error message if condition fails\&. 
.PP
\fBParameters\fP
.RS 4
\fIcond\fP boolean condition 
.br
\fImsg\fP message (std::string) 
.br
\fIf\fP file where jassert was called\&. 
.br
\fIline\fP line number where jassert was called\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
