.TH "jpcre2::INFO" 3 "Sat Aug 18 2018" "Version 10.31.02" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::INFO \- Namespace to provide information about JPCRE2 library itself\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "static const char \fBNAME\fP [] = 'JPCRE2'"
.br
.RI "Name of the project\&. "
.ti -1c
.RI "static const char \fBFULL_VERSION\fP [] = '10\&.31\&.02'"
.br
.RI "Full version string\&. "
.ti -1c
.RI "static const char \fBVERSION_GENRE\fP [] = '10'"
.br
.RI "Generation, depends on original PCRE2 version\&. "
.ti -1c
.RI "static const char \fBVERSION_MAJOR\fP [] = '31'"
.br
.RI "Major version, updated when API change is made\&. "
.ti -1c
.RI "static const char \fBVERSION_MINOR\fP [] = '02'"
.br
.RI "Minor version, includes bug fix or minor feature upgrade\&. "
.ti -1c
.RI "static const char \fBVERSION_PRE_RELEASE\fP [] = ''"
.br
.RI "Alpha or beta (testing) release version\&. "
.in -1c
.SH "Detailed Description"
.PP 
Namespace to provide information about JPCRE2 library itself\&. 

Contains constant Strings with version info\&. 
.SH "Variable Documentation"
.PP 
.SS "const char jpcre2::INFO::FULL_VERSION[] = '10\&.31\&.02'\fC [static]\fP"

.PP
Full version string\&. 
.SS "const char jpcre2::INFO::NAME[] = 'JPCRE2'\fC [static]\fP"

.PP
Name of the project\&. 
.SS "const char jpcre2::INFO::VERSION_GENRE[] = '10'\fC [static]\fP"

.PP
Generation, depends on original PCRE2 version\&. 
.SS "const char jpcre2::INFO::VERSION_MAJOR[] = '31'\fC [static]\fP"

.PP
Major version, updated when API change is made\&. 
.SS "const char jpcre2::INFO::VERSION_MINOR[] = '02'\fC [static]\fP"

.PP
Minor version, includes bug fix or minor feature upgrade\&. 
.SS "const char jpcre2::INFO::VERSION_PRE_RELEASE[] = ''\fC [static]\fP"

.PP
Alpha or beta (testing) release version\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
