jpcre2::select< Char_T, Map >::RegexReplace
NAME
jpcre2::select< Char_T, Map >::RegexReplace - Provides public constructors to create RegexReplace objects.
SYNOPSIS
#include <jpcre2.hpp>
Public Member Functions
RegexReplace ()
Default constructor.
RegexReplace (Regex const *r)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
RegexReplace (RegexReplace const &rr)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
RegexReplace & operator= (RegexReplace const &rr)
Overloaded Copy assignment operator.
RegexReplace (RegexReplace &&rr)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
RegexReplace & operator= (RegexReplace &&rr)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
RegexReplace & reset ()
Reset all class variables to its default (initial) state including memory.
RegexReplace & clear ()
Clear all class variables to its default (initial) state (some memory may retain for further use).
RegexReplace & resetErrors ()
Reset replace related errors to zero.
int getErrorNumber () const
Returns the last error number.
int getErrorOffset () const
Returns the last error offset.
String getErrorMessage () const
Returns the last error message.
String getReplaceWith () const
Get replacement string.
String const * getReplaceWithPointer () const
Get pointer to replacement string.
String getSubject () const
Get subject string.
String const * getSubjectPointer () const
Get pointer to subject string.
std::string getModifier () const
Calculate modifier string from PCRE2 and JPCRE2 options and return it.
ModifierTable const * getModifierTable ()
Get the modifier table that is set,.
PCRE2_SIZE getStartOffset () const
Get start offset.
Uint getPcre2Option () const
Get PCRE2 option.
Uint getJpcre2Option () const
Get JPCRE2 option.
Regex const * getRegexObject () const
Get a pointer to the associated Regex object.
MatchContext * getMatchContext ()
Return pointer to the match context that was previously set with setMatchContext().
virtual MatchData * getMatchDataBlock ()
Get the pointer to the match data block that was set previously with setMatchData() Handling memory is the callers' responsibility.
PCRE2_SIZE getBufferSize ()
Get the initial buffer size that is being used by internal function pcre2_substitute.
SIZE_T getLastReplaceCount ()
Get the number of replacement in last replace operation.
RegexReplace & setReplaceCounter (SIZE_T *counter)
Set an external counter variable to store the replacement count.
RegexReplace & setRegexObject (Regex const *r)
Set the associated Regex object.
RegexReplace & setSubject (String const &s)
Set the subject string for replace.
RegexReplace & setSubject (String *s)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
RegexReplace & setReplaceWith (String const &s)
Set the replacement string.
RegexReplace & setReplaceWith (String const *s)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
RegexReplace & setModifier (Modifier const &s)
Set the modifier string (resets all JPCRE2 and PCRE2 options) by calling RegexReplace::changeModifier().
RegexReplace & setModifierTable (ModifierTable const *mdt)
Set a custom modifier table to be used.
RegexReplace & setBufferSize (PCRE2_SIZE x)
Set the initial buffer size to be allocated for replaced string (used by PCRE2)
RegexReplace & setStartOffset (PCRE2_SIZE start_offset)
Set start offset.
RegexReplace & setJpcre2Option (Uint x)
Set JPCRE2 option for replace (overwrite existing option)
RegexReplace & setPcre2Option (Uint x)
Set PCRE2 option replace (overwrite existing option)
RegexReplace & setMatchContext (MatchContext *match_context)
Set the match context to be used.
RegexReplace & setMatchDataBlock (MatchData *match_data)
Set the match data block to be used.
RegexReplace & changeModifier (Modifier const &mod, bool x)
After a call to this function PCRE2 and JPCRE2 options will be properly set.
RegexReplace & changeJpcre2Option (Uint opt, bool x)
Parse modifier and add/remove equivalent PCRE2 and JPCRE2 options.
RegexReplace & changePcre2Option (Uint opt, bool x)
Add or remove a PCRE2 option.
RegexReplace & addModifier (Modifier const &mod)
Parse modifier string and add equivalent PCRE2 and JPCRE2 options.
RegexReplace & addJpcre2Option (Uint x)
Add specified JPCRE2 option to existing options for replace.
RegexReplace & addPcre2Option (Uint x)
Add specified PCRE2 option to existing options for replace.
String replace (void)
Perform regex replace by retrieving subject string, replacement string, modifier and other options from class variables.
SIZE_T preplace (void)
Perl compatible replace method.
SIZE_T preplace (MatchEvaluator me)
Perl compatible replace method with match evaluator.
String nreplace (MatchEvaluator me)
JPCRE2 native replace function.
String replace (MatchEvaluator me)
PCRE2 compatible replace function that takes a MatchEvaluator.
Detailed Description
template<typename Char_T, template< typename... > class Map = std::map>
class jpcre2::select< Char_T, Map >::RegexReplace"
Provides public constructors to create RegexReplace objects.
Every RegexReplace object should be associated with a Regex object. This class stores a pointer to its' associated Regex object, thus when the content of the associated Regex object is changed, there's no need to set the pointer again.
Examples:
jp::Regex re;
jp::RegexReplace rr;
rr.setRegexObject(&re);
rr.replace("subject", "me"); // returns 'subject'
re.compile("\w+");
rr.replace(); // replaces 'subject' with 'me' i.e returns 'me'
Constructor & Destructor Documentation
template<typename Char_T, template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::RegexReplace::RegexReplace () [inline]
Default constructor.
template<typename Char_T, template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::RegexReplace::RegexReplace (Regex const * r) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Creates a RegexReplace object associating a Regex object. Regex object is not modified.
Parameters:
r pointer to a Regex object
template<typename Char_T, template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::RegexReplace::RegexReplace (RegexReplace const & rr) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Copy constructor.
Parameters:
rr RegexReplace object reference
template<typename Char_T, template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::RegexReplace::RegexReplace (RegexReplace && rr) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Move constructor. This constructor steals resources from the argument. It leaves the argument in a valid but indeterminate sate. The indeterminate state can be returned to normal by calling reset() on that object.
Parameters:
rr rvalue reference to a RegexReplace object reference
Member Function Documentation
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::addJpcre2Option (Uint x) [inline]
Add specified JPCRE2 option to existing options for replace.
Parameters:
x Option value
Returns:
Reference to the calling RegexReplace object
See also:
RegexMatch::addJpcre2Option()
Regex::addJpcre2Option()
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::addModifier (Modifier const & mod) [inline]
Parse modifier string and add equivalent PCRE2 and JPCRE2 options. This is just a wrapper of the original function RegexReplace::changeModifier() provided for convenience.
Parameters:
mod Modifier string.
Returns:
Reference to the calling RegexReplace object
See also:
RegexMatch::addModifier()
Regex::addModifier()
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::addPcre2Option (Uint x) [inline]
Add specified PCRE2 option to existing options for replace.
Parameters:
x Option value
Returns:
Reference to the calling RegexReplace object
See also:
RegexMatch::addPcre2Option()
Regex::addPcre2Option()
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::changeJpcre2Option (Uint opt, bool x) [inline]
Parse modifier and add/remove equivalent PCRE2 and JPCRE2 options. Add or remove a JPCRE2 option
Parameters:
opt JPCRE2 option value
x Add the option if it's true, remove otherwise.
Returns:
Reference to the calling RegexReplace object
See also:
RegexMatch::changeJpcre2Option()
Regex::changeJpcre2Option()
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::changeModifier (Modifier const & mod, bool x) [inline]
After a call to this function PCRE2 and JPCRE2 options will be properly set. This function does not initialize or re-initialize options. If you want to set options from scratch, initialize them to 0 before calling this function.
If invalid modifier is detected, then the error number for the RegexReplace object will be jpcre2::ERROR::INVALID_MODIFIER and error offset will be the modifier character. You can get the message with RegexReplace::getErrorMessage() function.
Parameters:
mod Modifier string.
x Whether to add or remove option
Returns:
Reference to the RegexReplace object
See also:
Regex::changeModifier()
RegexMatch::changeModifier()
References jpcre2::ModifierTable::toReplaceOption().
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::changePcre2Option (Uint opt, bool x) [inline]
Add or remove a PCRE2 option.
Parameters:
opt PCRE2 option value
x Add the option if it's true, remove otherwise.
Returns:
Reference to the calling RegexReplace object
See also:
RegexMatch::changePcre2Option()
Regex::changePcre2Option()
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::clear () [inline]
Clear all class variables to its default (initial) state (some memory may retain for further use).
Returns:
Reference to the calling RegexReplace object.
References jpcre2::select< Char_T, Map >::RegexReplace::clear().
Referenced by jpcre2::select< Char_T, Map >::RegexReplace::clear(), jpcre2::select< Char_T, Map >::RegexReplace::setReplaceWith(), and jpcre2::select< Char_T, Map >::RegexReplace::setSubject().
template<typename Char_T, template< typename... > class Map = std::map> PCRE2_SIZE jpcre2::select< Char_T, Map >::RegexReplace::getBufferSize () [inline]
Get the initial buffer size that is being used by internal function pcre2_substitute.
Returns:
buffer_size
template<typename Char_T, template< typename... > class Map = std::map> String jpcre2::select< Char_T, Map >::RegexReplace::getErrorMessage () const [inline]
Returns the last error message.
Returns:
Last error message
References jpcre2::select< Char_T, Map >::getErrorMessage().
template<typename Char_T, template< typename... > class Map = std::map> int jpcre2::select< Char_T, Map >::RegexReplace::getErrorNumber () const [inline]
Returns the last error number.
Returns:
Last error number
template<typename Char_T, template< typename... > class Map = std::map> int jpcre2::select< Char_T, Map >::RegexReplace::getErrorOffset () const [inline]
Returns the last error offset.
Returns:
Last error offset
template<typename Char_T, template< typename... > class Map = std::map> Uint jpcre2::select< Char_T, Map >::RegexReplace::getJpcre2Option () const [inline]
Get JPCRE2 option.
Returns:
JPCRE2 option for replace
See also:
Regex::getJpcre2Option()
RegexMatch::getJpcre2Option()
template<typename Char_T, template< typename... > class Map = std::map> SIZE_T jpcre2::select< Char_T, Map >::RegexReplace::getLastReplaceCount () [inline]
Get the number of replacement in last replace operation. If you set an external counter with RegexReplace::setReplaceCounter(), a call to this getter method will dereference the pointer to the external counter and return the value.
Returns:
Last replace count
template<typename Char_T, template< typename... > class Map = std::map> MatchContext* jpcre2::select< Char_T, Map >::RegexReplace::getMatchContext () [inline]
Return pointer to the match context that was previously set with setMatchContext(). Handling memory is the callers' responsibility.
Returns:
pointer to the match context (default: null).
template<typename Char_T, template< typename... > class Map = std::map> virtual MatchData* jpcre2::select< Char_T, Map >::RegexReplace::getMatchDataBlock () [inline], [virtual]
Get the pointer to the match data block that was set previously with setMatchData() Handling memory is the callers' responsibility.
Returns:
pointer to the match data (default: null).
template<typename Char_T, template< typename... > class Map = std::map> std::string jpcre2::select< Char_T, Map >::RegexReplace::getModifier () const [inline]
Calculate modifier string from PCRE2 and JPCRE2 options and return it. Do remember that modifiers (or PCRE2 and JPCRE2 options) do not change or get initialized as long as you don't do that explicitly. Calling RegexReplace::setModifier() will re-set them.
Mixed or combined modifier.
Some modifier may include other modifiers i.e they have the same meaning of some modifiers combined together. For example, the 'n' modifier includes the 'u' modifier and together they are equivalent to PCRE2_UTF | PCRE2_UCP. When you set a modifier like this, both options get set, and when you remove the 'n' modifier (with RegexReplace::changeModifier()), both will get removed.
Returns:
Calculated modifier string (std::string)
See also:
RegexMatch::getModifier()
Regex::getModifier()
References jpcre2::ModifierTable::fromReplaceOption().
template<typename Char_T, template< typename... > class Map = std::map> ModifierTable const* jpcre2::select< Char_T, Map >::RegexReplace::getModifierTable () [inline]
Get the modifier table that is set,.
Returns:
constant ModifierTable pointer.
template<typename Char_T, template< typename... > class Map = std::map> Uint jpcre2::select< Char_T, Map >::RegexReplace::getPcre2Option () const [inline]
Get PCRE2 option.
Returns:
PCRE2 option for replace
See also:
Regex::getPcre2Option()
RegexMatch::getPcre2Option()
template<typename Char_T, template< typename... > class Map = std::map> Regex const* jpcre2::select< Char_T, Map >::RegexReplace::getRegexObject () const [inline]
Get a pointer to the associated Regex object. If no actual Regex object is associated, null is returned
Returns:
A pointer to the associated constant Regex object or null
template<typename Char_T, template< typename... > class Map = std::map> String jpcre2::select< Char_T, Map >::RegexReplace::getReplaceWith () const [inline]
Get replacement string.
Returns:
replacement string
template<typename Char_T, template< typename... > class Map = std::map> String const* jpcre2::select< Char_T, Map >::RegexReplace::getReplaceWithPointer () const [inline]
Get pointer to replacement string.
Returns:
pointer to replacement string
template<typename Char_T, template< typename... > class Map = std::map> PCRE2_SIZE jpcre2::select< Char_T, Map >::RegexReplace::getStartOffset () const [inline]
Get start offset.
Returns:
the start offset where matching starts for replace operation
template<typename Char_T, template< typename... > class Map = std::map> String jpcre2::select< Char_T, Map >::RegexReplace::getSubject () const [inline]
Get subject string.
Returns:
subject string
See also:
RegexMatch::getSubject()
template<typename Char_T, template< typename... > class Map = std::map> String const* jpcre2::select< Char_T, Map >::RegexReplace::getSubjectPointer () const [inline]
Get pointer to subject string.
Returns:
Pointer to constant subject string
See also:
RegexMatch::getSubjectPointer()
template<typename Char_T, template< typename... > class Map = std::map> String jpcre2::select< Char_T, Map >::RegexReplace::nreplace (MatchEvaluator me) [inline]
JPCRE2 native replace function. A different name is adopted to distinguish itself from the regular replace() function which uses pcre2_substitute() to do the replacement; contrary to that, it will provide a JPCRE2 native way of replacement operation. It takes a MatchEvaluator object which provides a callback function that is used to generate replacement string on the fly. Any replacement string set with RegexReplace::setReplaceWith() function will have no effect. The string returned by the callback function will be treated as literal and will not go through any further processing.
This function works on a copy of the MatchEvaluator, and thus makes no changes to the original. The copy is modified as below:
1.
Global replacement will set FIND_ALL for match, unset otherwise.
2.
Bad matching options such as PCRE2_PARTIAL_HARD|PCRE2_PARTIAL_SOFT will be removed.
3.
subject, start_offset and Regex object will change according to the RegexReplace object.
4.
match context, and match data block will be changed according to the RegexReplace object.
It calls MatchEvaluator::nreplace() on the MatchEvaluator object to perform the replacement.
It always performs a new match.
Parameters:
me A MatchEvaluator object.
Returns:
The resultant string after replacement.
See also:
MatchEvaluator::nreplace()
MatchEvaluator
MatchEvaluatorCallback
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::operator= (RegexReplace const & rr) [inline]
Overloaded Copy assignment operator.
Parameters:
rr RegexReplace object reference
Returns:
A reference to the calling RegexReplace object
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::operator= (RegexReplace && rr) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Overloaded move assignment operator. This constructor steals resources from the argument. It leaves the argument in a valid but indeterminate sate. The indeterminate state can be returned to normal by calling reset() on that object.
Parameters:
rr rvalue reference to a RegexReplace object reference
Returns:
A reference to the calling RegexReplace object
template<typename Char_T, template< typename... > class Map = std::map> SIZE_T jpcre2::select< Char_T, Map >::RegexReplace::preplace (void) [inline]
Perl compatible replace method. Modifies subject string in-place and returns replace count.
The replacement is performed with RegexReplace::replace() which uses pcre2_substitute().
Returns:
replace count
template<typename Char_T, template< typename... > class Map = std::map> SIZE_T jpcre2::select< Char_T, Map >::RegexReplace::preplace (MatchEvaluator me) [inline]
Perl compatible replace method with match evaluator. Modifies subject string in-place and returns replace count. MatchEvaluator class does not have a implementation of this replace method, thus it is not possible to re-use match data with preplace() method. Re-using match data with preplace doesn't actually make any sense, because new subject will always require new match data.
The replacement is performed with RegexReplace::replace() which uses pcre2_substitute().
Parameters:
me MatchEvaluator object.
Returns:
replace count
template<typename Char_T , template< typename... > class Map> jpcre2::select< Char_T, Map >::String jpcre2::select< Char_T, Map >::RegexReplace::replace (void)
Perform regex replace by retrieving subject string, replacement string, modifier and other options from class variables. In the replacement string (see RegexReplace::setReplaceWith()) $ is a special character which implies captured group.
1.
A numbered substring can be referenced with $n or ${n} where n is the group number.
2.
A named substring can be referenced with ${name}, where 'name' is the group name.
3.
A literal $ can be given as $$.
4.
Bash like features: ${<n>:-<string>} and ${<n>:+<string1>:<string2>}, where <n> is a group number or name.
All options supported by pcre2_substitute is available.
Note: This function calls pcre2_substitute() to do the replacement.
Returns:
Replaced string
template<typename Char_T, template< typename... > class Map = std::map> String jpcre2::select< Char_T, Map >::RegexReplace::replace (MatchEvaluator me) [inline]
PCRE2 compatible replace function that takes a MatchEvaluator. String returned by callback function is processed by pcre2_substitute, thus all PCRE2 substitute options are supported by this replace function.
It always performs a new match.
Parameters:
me MatchEvaluator instance, (copied and modified according to this object).
Returns:
resultant string.
See also:
replace()
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::reset () [inline]
Reset all class variables to its default (initial) state including memory.
Returns:
Reference to the calling RegexReplace object.
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::resetErrors () [inline]
Reset replace related errors to zero.
Returns:
Reference to the calling RegexReplace object
See also:
Regex::resetErrors()
RegexMatch::resetErrors()
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::setBufferSize (PCRE2_SIZE x) [inline]
Set the initial buffer size to be allocated for replaced string (used by PCRE2)
Parameters:
x Buffer size
Returns:
Reference to the calling RegexReplace object
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::setJpcre2Option (Uint x) [inline]
Set JPCRE2 option for replace (overwrite existing option)
Parameters:
x Option value
Returns:
Reference to the calling RegexReplace object
See also:
RegexMatch::setJpcre2Option()
Regex::setJpcre2Option()
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::setMatchContext (MatchContext * match_context) [inline]
Set the match context to be used. Native PCRE2 API may be used to create match context. The memory of the match context is not handled by RegexReplace object and not freed. User will be responsible for freeing memory.
Parameters:
match_context Pointer to match context.
Returns:
Reference to the calling RegexReplace object.
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::setMatchDataBlock (MatchData * match_data) [inline]
Set the match data block to be used. Native PCRE2 API may be used to create match data block. The memory of the match data is not handled by RegexReplace object and not freed. User will be responsible for creating/freeing memory.
Parameters:
match_data Pointer to match data.
Returns:
Reference to the calling RegexReplace object.
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::setModifier (Modifier const & s) [inline]
Set the modifier string (resets all JPCRE2 and PCRE2 options) by calling RegexReplace::changeModifier().
Parameters:
s Modifier string.
Returns:
Reference to the calling RegexReplace object
See also:
RegexMatch::setModifier()
Regex::setModifier()
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::setModifierTable (ModifierTable const * mdt) [inline]
Set a custom modifier table to be used.
Parameters:
mdt pointer to ModifierTable object.
Returns:
Reference to the calling RegexReplace object.
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::setPcre2Option (Uint x) [inline]
Set PCRE2 option replace (overwrite existing option)
Parameters:
x Option value
Returns:
Reference to the calling RegexReplace object
See also:
RegexMatch::setPcre2Option()
Regex::setPcre2Option()
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::setRegexObject (Regex const * r) [inline]
Set the associated Regex object. Regex object is not modified.
Parameters:
r Pointer to a Regex object.
Returns:
Reference to the calling RegexReplace object.
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::setReplaceCounter (SIZE_T * counter) [inline]
Set an external counter variable to store the replacement count. This counter will be updated after each replacement operation on this object. A call to this method will reset the internal counter to 0, thus when you reset the counter to internal counter (by giving null as param), the previous replace count won't be available.
Parameters:
counter Pointer to a counter variable. Null sets the counter to default internal counter.
Returns:
Reference to the calling RegexReplace object.
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::setReplaceWith (String const & s) [inline]
Set the replacement string. $ is a special character which implies captured group.
1.
A numbered substring can be referenced with $n or ${n} where n is the group number.
2.
A named substring can be referenced with ${name}, where 'name' is the group name.
3.
A literal $ can be given as $$.
Note: This function makes a copy of the string. If no copy is desired or you are working with big text, consider passing the string with pointer.
Parameters:
s String to replace with
Returns:
Reference to the calling RegexReplace object
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::setReplaceWith (String const * s) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
Parameters:
s Pointer to the string to replace with, null pointer unsets it.
Returns:
Reference to the calling RegexReplace object
References jpcre2::select< Char_T, Map >::RegexReplace::clear().
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::setStartOffset (PCRE2_SIZE start_offset) [inline]
Set start offset. Set the offset where matching starts for replace operation
Parameters:
start_offset The offset where matching starts for replace operation
Returns:
Reference to the calling RegexReplace object
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::setSubject (String const & s) [inline]
Set the subject string for replace. This makes a copy of the string. If no copy is desired or you are working with big text, consider passing by pointer.
Parameters:
s Subject string
Returns:
Reference to the calling RegexReplace object
See also:
RegexMatch::setSubject()
template<typename Char_T, template< typename... > class Map = std::map> RegexReplace& jpcre2::select< Char_T, Map >::RegexReplace::setSubject (String * s) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Set pointer to the subject string for replace, null pointer unsets it. The underlined data is not modified unless RegexReplace::preplace() method is used.
Parameters:
s Pointer to subject string
Returns:
Reference to the calling RegexReplace object
See also:
RegexMatch::setSubject()
References jpcre2::select< Char_T, Map >::RegexReplace::clear().
Author
Generated automatically by Doxygen for JPCRE2 from the source code.