jpcre2::select< Char_T, Map >::MatchEvaluator
NAME
jpcre2::select< Char_T, Map >::MatchEvaluator - This class inherits RegexMatch and provides a similar functionality.
SYNOPSIS
#include <jpcre2.hpp>
Public Member Functions
MatchEvaluator ()
Default constructor.
MatchEvaluator (Regex const *r)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator (typename MatchEvaluatorCallback< void *, void *, void * >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator (typename MatchEvaluatorCallback< NumSub const &, void *, void * >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator (typename MatchEvaluatorCallback< NumSub const &, MapNas const &, void * >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator (typename MatchEvaluatorCallback< NumSub const &, void *, MapNtN const & >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator (typename MatchEvaluatorCallback< NumSub const &, MapNas const &, MapNtN const & >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator (typename MatchEvaluatorCallback< void *, MapNas const &, void * >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator (typename MatchEvaluatorCallback< void *, MapNas const &, MapNtN const & >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator (typename MatchEvaluatorCallback< void *, void *, MapNtN const & >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator (MatchEvaluator const &me)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator & operator= (MatchEvaluator const &me)
Overloaded copy-assignment operator.
MatchEvaluator (MatchEvaluator &&me)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator & operator= (MatchEvaluator &&me)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator & setCallback (typename MatchEvaluatorCallback< void *, void *, void * >::Callback mef)
Member function to set a callback function with no vector reference.
MatchEvaluator & setCallback (typename MatchEvaluatorCallback< NumSub const &, void *, void * >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator & setCallback (typename MatchEvaluatorCallback< NumSub const &, MapNas const &, void * >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator & setCallback (typename MatchEvaluatorCallback< NumSub const &, void *, MapNtN const & >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator & setCallback (typename MatchEvaluatorCallback< NumSub const &, MapNas const &, MapNtN const & >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator & setCallback (typename MatchEvaluatorCallback< void *, MapNas const &, void * >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator & setCallback (typename MatchEvaluatorCallback< void *, MapNas const &, MapNtN const & >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator & setCallback (typename MatchEvaluatorCallback< void *, void *, MapNtN const & >::Callback mef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
MatchEvaluator & clearMatchData ()
Clear match data.
MatchEvaluator & resetMatchData ()
Reset match data to initial state.
MatchEvaluator & reset ()
Reset MatchEvaluator to initial state including memory.
MatchEvaluator & clear ()
Clears MatchEvaluator.
MatchEvaluator & resetErrors ()
Call RegexMatch::resetErrors().
MatchEvaluator & setRegexObject (Regex const *r)
Call RegexMatch::setRegexObject(r).
MatchEvaluator & setSubject (String const &s)
Call RegexMatch::setSubject(String const &s).
MatchEvaluator & setSubject (String const *s)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
MatchEvaluator & setModifier (Modifier const &s)
Call RegexMatch::setModifier(Modifier const& s).
MatchEvaluator & setModifierTable (ModifierTable const *mdt)
Call RegexMatch::setModifierTable(ModifierTable const * s).
MatchEvaluator & setJpcre2Option (Uint x)
Call RegexMatch::setJpcre2Option(Uint x).
MatchEvaluator & setPcre2Option (Uint x)
Call RegexMatch::setPcre2Option (Uint x).
MatchEvaluator & setFindAll (bool x)
Call RegexMatch::setFindAll(bool x).
MatchEvaluator & setFindAll ()
Call RegexMatch::setFindAll().
MatchEvaluator & setStartOffset (PCRE2_SIZE offset)
Call RegexMatch::setStartOffset (PCRE2_SIZE offset).
MatchEvaluator & setMatchContext (MatchContext *match_context)
Call RegexMatch::setMatchContext(MatchContext *match_context).
MatchEvaluator & setMatchDataBlock (MatchData *mdt)
Call RegexMatch::setMatchDataBlock(MatchContext * mdt);.
MatchEvaluator & setBufferSize (PCRE2_SIZE x)
Set the buffer size that will be used by pcre2_substitute (replace()).
PCRE2_SIZE getBufferSize ()
Get the initial buffer size that is being used by internal function pcre2_substitute.
MatchEvaluator & changeModifier (Modifier const &mod, bool x)
Call RegexMatch::changeModifier(Modifier const& mod, bool x).
MatchEvaluator & changeJpcre2Option (Uint opt, bool x)
Call RegexMatch::changeJpcre2Option(Uint opt, bool x).
MatchEvaluator & changePcre2Option (Uint opt, bool x)
Call RegexMatch::changePcre2Option(Uint opt, bool x).
MatchEvaluator & addModifier (Modifier const &mod)
Call RegexMatch::addModifier(Modifier const& mod).
MatchEvaluator & addJpcre2Option (Uint x)
Call RegexMatch::addJpcre2Option(Uint x).
MatchEvaluator & addPcre2Option (Uint x)
Call RegexMatch::addPcre2Option(Uint x).
SIZE_T match (void)
Perform match and return the match count.
String nreplace (bool do_match=true, Uint jro=0, SIZE_T *counter=0)
Perform regex replace with this match evaluator.
String replace (bool do_match=true, Uint ro=0, SIZE_T *counter=0)
PCRE2 compatible replace function that uses this MatchEvaluator.
virtual int getErrorNumber () const
Returns the last error number.
virtual int getErrorOffset () const
Returns the last error offset.
virtual String getErrorMessage () const
Returns the last error message.
virtual String getSubject () const
Get subject string (by value).
virtual const String * getSubjectPointer () const
Get pointer to subject string.
virtual std::string getModifier () const
Calculate modifier string from PCRE2 and JPCRE2 options and return it.
virtual ModifierTable const * getModifierTable ()
Get the modifier table that is set,.
virtual Uint getPcre2Option () const
Get PCRE2 option.
virtual Uint getJpcre2Option () const
Get JPCRE2 option.
virtual PCRE2_SIZE getStartOffset () const
Get offset from where match will start in the subject.
virtual VecOff const * getMatchStartOffsetVector () const
Get pre-set match start offset vector pointer.
virtual VecOff const * getMatchEndOffsetVector () const
Get pre-set match end offset vector pointer.
virtual const Regex * getRegexObject () const
Get a pointer to the associated Regex object.
virtual VecNum const * getNumberedSubstringVector () const
Get pointer to numbered substring vector.
virtual VecNas const * getNamedSubstringVector () const
Get pointer to named substring vector.
virtual VecNtN const * getNameToNumberMapVector () const
Get pointer to name to number map vector.
virtual MatchContext * getMatchContext ()
Return pointer to the match context that was previously set with setMatchContext().
virtual MatchData * getMatchDataBlock ()
Get the pointer to the match data block that was set previously with setMatchData() Handling memory is the callers' responsibility.
Detailed Description
template<typename Char_T, template< typename... > class Map = std::map>
class jpcre2::select< Char_T, Map >::MatchEvaluator"
This class inherits RegexMatch and provides a similar functionality.
All public member functions from RegexMatch class are publicly available except the following:
setNumberedSubstringVector
setNamedSubstringVector
setNameToNumberMapVector
setMatchStartOffsetVector
setMatchEndOffsetVector
The use of above functions is not allowed as the vectors are created according to the callback function you pass.
Each constructor of this class takes a callback function as argument (see MatchEvaluatorCallback).
It provides a MatchEvaluator::nreplace() function to perform replace operation using native JPCRE2 approach and MatchEvaluator::replace() function for PCRE2 compatible replace operation.
An instance of this class can also be passed with RegexReplace::nreplace() or RegexReplace::replace() function to perform replacement according to this match evaluator.
Match data is stored in vectors, and the vectors are populated according to the callback functions. Populated vector data is never deleted but they get overwritten. Vector data can be manually zeroed out by calling MatchEvaluator::clearMatchData(). If the capacities of those match vectors are desired to to be shrinked too instead of just clearing them, use MatchEvaluator::resetMatchData() instead.
Re-usability of Match Data
A match data populated with a callback function that takes only a jp::NumSub vector is not compatible with the data created according to callback function with a jp::MapNas vector. Because, for this later callback, jp::MapNas data is required but is not available (only jp::NumSub is available). In such cases, previous Match data can not be used to perform a new replacment operation with this second callback function.
To populate the match vectors, one must call the MatchEvaluator::match() or MatchEvaluator::nreplace() function, they will populate vectors with match data according to call back function.
Example:
jp::String callback5(NumSub const &m, void*, MapNtn const &n){
    return m[0];
}
jp::String callback4(void*, void*, MapNtn const &n){
    return std::to_string(n.at("name")); //position of group 'name'.
}
jp::String callback2(void*, MapNas const &m, void*){
    return m.at('name'); //substring by name
}
jp::MatchEvaluator me;
me.setRegexObject(&re).setSubject("string").setCallback(callback5).nreplace();
//In above, nreplace() populates jp::NumSub and jp::MapNtn with match data.
me.setCallback(callback4).nreplace(false);
//the above uses previous match result (note the 'false') which is OK,
//because, callback4 requires jp::MapNtn which was made available in the previous operation.
//but the following is not OK: (assertion failure)
me.setCallback(callback2).nreplace(false);
//because, callback2 requires jp::MapNas data which is not available.
//now, this is OK:
me.setCallback(callback2).nreplace();
//because, it will recreate those match data including this one (jp::MapNas).
Replace options
MatchEvaluator can not take replace options. Replace options are taken directly by the replace functions: nreplace() and replace().
Using as a match object
As it's just a subclass of RegexMatch, it can do all the things that RegexMatch can do, with some restrictions:
matching options are modified to strip off bad options according to replacement (PCRE2_PARTIAL_HARD|PCRE2_PARTIAL_SOFT).
match depends on the callback function. Only those vectors will be populated that are implemented by the callback functions so far (multiple callback function will set multiple match data vectors.)
match vectors are internal to this class, you can not set them manually (without callback function). (you can get pointers to these vectors with getNumberedSubstringVector() and related functions).
See also
MatchEvaluatorCallback
RegexReplace::nreplace()
Constructor & Destructor Documentation
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::MatchEvaluator::MatchEvaluator () [inline], [explicit]
Default constructor. Sets callback::erase as the callback function. Removes matched part/s from the subject string if the callback is not changed.
jp::Regex re("\s*string");
jp::MatchEvaluator me;
std::cout<<
me.setRegexObject(&re);
  .setSubject("I am a string");
  .nreplace();
//The above will delete ' string' from the subject
//thus the result will be 'I am a'
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::MatchEvaluator::MatchEvaluator (Regex const * r) [inline], [explicit]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Constructor taking a Regex object pointer. It sets the associated Regex object and initializes the MatchEvaluator object with callback::erase callback function. Underlying data is not modified.
Parameters
r constant Regex pointer.
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::MatchEvaluator::MatchEvaluator (typename MatchEvaluatorCallback< void *, void *, void * >::Callback mef) [inline], [explicit]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Constructor taking a callback function. It calls a corresponding MatchEvaluator::setCallback() function to set the callback function.
Parameters
mef Callback function.
References jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback().
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::MatchEvaluator::MatchEvaluator (typename MatchEvaluatorCallback< NumSub const &, void *, void * >::Callback mef) [inline], [explicit]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... It calls a corresponding MatchEvaluator::setCallback() function to set the callback function.
Parameters
mef Callback function.
References jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback().
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::MatchEvaluator::MatchEvaluator (typename MatchEvaluatorCallback< NumSub const &, MapNas const &, void * >::Callback mef) [inline], [explicit]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... It calls a corresponding MatchEvaluator::setCallback() function to set the callback function.
Parameters
mef Callback function.
References jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback().
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::MatchEvaluator::MatchEvaluator (typename MatchEvaluatorCallback< NumSub const &, void *, MapNtN const & >::Callback mef) [inline], [explicit]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... It calls a corresponding MatchEvaluator::setCallback() function to set the callback function.
Parameters
mef Callback function.
References jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback().
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::MatchEvaluator::MatchEvaluator (typename MatchEvaluatorCallback< NumSub const &, MapNas const &, MapNtN const & >::Callback mef) [inline], [explicit]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... It calls a corresponding MatchEvaluator::setCallback() function to set the callback function.
Parameters
mef Callback function.
References jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback().
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::MatchEvaluator::MatchEvaluator (typename MatchEvaluatorCallback< void *, MapNas const &, void * >::Callback mef) [inline], [explicit]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... It calls a corresponding MatchEvaluator::setCallback() function to set the callback function.
Parameters
mef Callback function.
References jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback().
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::MatchEvaluator::MatchEvaluator (typename MatchEvaluatorCallback< void *, MapNas const &, MapNtN const & >::Callback mef) [inline], [explicit]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... It calls a corresponding MatchEvaluator::setCallback() function to set the callback function.
Parameters
mef Callback function.
References jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback().
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::MatchEvaluator::MatchEvaluator (typename MatchEvaluatorCallback< void *, void *, MapNtN const & >::Callback mef) [inline], [explicit]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... It calls a corresponding MatchEvaluator::setCallback() function to set the callback function.
Parameters
mef Callback function.
References jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback().
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::MatchEvaluator::MatchEvaluator (MatchEvaluator const & me) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Copy constructor.
Parameters
me Reference to MatchEvaluator object
template<typename Char_T , template< typename... > class Map = std::map> jpcre2::select< Char_T, Map >::MatchEvaluator::MatchEvaluator (MatchEvaluator && me) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Move constructor. This constructor steals resources from the argument. It leaves the argument in a valid but indeterminate sate. The indeterminate state can be returned to normal by calling reset() on that object.
Parameters
me rvalue reference to a MatchEvaluator object
Member Function Documentation
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::addJpcre2Option (Uint x) [inline], [virtual]
Call RegexMatch::addJpcre2Option(Uint x).
Parameters
x JPCRE2 option.
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::addJpcre2Option().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::addModifier (Modifier const & mod) [inline], [virtual]
Call RegexMatch::addModifier(Modifier const& mod).
Parameters
mod modifier string.
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::addModifier().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::addPcre2Option (Uint x) [inline], [virtual]
Call RegexMatch::addPcre2Option(Uint x).
Parameters
x PCRE2 option.
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::addPcre2Option().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::changeJpcre2Option (Uint opt, bool x) [inline], [virtual]
Call RegexMatch::changeJpcre2Option(Uint opt, bool x).
Parameters
opt JPCRE2 option
x true (add) or false (remove).
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::changeJpcre2Option().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::changeModifier (Modifier const & mod, bool x) [inline], [virtual]
Call RegexMatch::changeModifier(Modifier const& mod, bool x).
Parameters
mod modifier string.
x true (add) or false (remove).
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::changeModifier().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::changePcre2Option (Uint opt, bool x) [inline], [virtual]
Call RegexMatch::changePcre2Option(Uint opt, bool x).
Parameters
opt PCRE2 option.
x true (add) or false (remove).
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::changePcre2Option().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::clear () [inline], [virtual]
Clears MatchEvaluator. Returns everything to initial state (some memory may retain for further and faster use).
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::clear(), and jpcre2::select< Char_T, Map >::MatchEvaluator::clearMatchData().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::clearMatchData () [inline]
Clear match data. It clears all match data from all vectors (without shrinking). For shrinking the vectors, use resetMatchData() A call to match() or nreplace() will be required to produce match data again.
Returns
A reference to the calling MatchEvaluator object.
Referenced by jpcre2::select< Char_T, Map >::MatchEvaluator::clear().
template<typename Char_T , template< typename... > class Map = std::map> PCRE2_SIZE jpcre2::select< Char_T, Map >::MatchEvaluator::getBufferSize () [inline]
Get the initial buffer size that is being used by internal function pcre2_substitute.
Returns
buffer_size
template<typename Char_T , template< typename... > class Map = std::map> virtual String jpcre2::select< Char_T, Map >::RegexMatch::getErrorMessage () const [inline], [virtual], [inherited]
Returns the last error message.
Returns
Last error message
References jpcre2::select< Char_T, Map >::getErrorMessage().
template<typename Char_T , template< typename... > class Map = std::map> virtual int jpcre2::select< Char_T, Map >::RegexMatch::getErrorNumber () const [inline], [virtual], [inherited]
Returns the last error number.
Returns
Last error number
template<typename Char_T , template< typename... > class Map = std::map> virtual int jpcre2::select< Char_T, Map >::RegexMatch::getErrorOffset () const [inline], [virtual], [inherited]
Returns the last error offset.
Returns
Last error offset
template<typename Char_T , template< typename... > class Map = std::map> virtual Uint jpcre2::select< Char_T, Map >::RegexMatch::getJpcre2Option () const [inline], [virtual], [inherited]
Get JPCRE2 option.
Returns
JPCRE2 options for math operation
See also
Regex::getJpcre2Option()
RegexReplace::getJpcre2Option()
template<typename Char_T , template< typename... > class Map = std::map> virtual MatchContext* jpcre2::select< Char_T, Map >::RegexMatch::getMatchContext () [inline], [virtual], [inherited]
Return pointer to the match context that was previously set with setMatchContext(). Handling memory is the callers' responsibility.
Returns
pointer to the match context (default: null).
template<typename Char_T , template< typename... > class Map = std::map> virtual MatchData* jpcre2::select< Char_T, Map >::RegexMatch::getMatchDataBlock () [inline], [virtual], [inherited]
Get the pointer to the match data block that was set previously with setMatchData() Handling memory is the callers' responsibility.
Returns
pointer to the match data (default: null).
template<typename Char_T , template< typename... > class Map = std::map> virtual VecOff const* jpcre2::select< Char_T, Map >::RegexMatch::getMatchEndOffsetVector () const [inline], [virtual], [inherited]
Get pre-set match end offset vector pointer. The pointer must be set with RegexMatch::setMatchEndOffsetVector() beforehand for this to work i.e it is just a convenience method to get the pre-set vector pointer.
Returns
pointer to the const end offset vector
template<typename Char_T , template< typename... > class Map = std::map> virtual VecOff const* jpcre2::select< Char_T, Map >::RegexMatch::getMatchStartOffsetVector () const [inline], [virtual], [inherited]
Get pre-set match start offset vector pointer. The pointer must be set with RegexMatch::setMatchStartOffsetVector() beforehand for this to work i.e it is just a convenience method to get the pre-set vector pointer.
Returns
pointer to the const match start offset vector
template<typename Char_T , template< typename... > class Map = std::map> virtual std::string jpcre2::select< Char_T, Map >::RegexMatch::getModifier () const [inline], [virtual], [inherited]
Calculate modifier string from PCRE2 and JPCRE2 options and return it. Do remember that modifiers (or PCRE2 and JPCRE2 options) do not change or get initialized as long as you don't do that explicitly. Calling RegexMatch::setModifier() will re-set them.
Mixed or combined modifier.
Some modifier may include other modifiers i.e they have the same meaning of some modifiers combined together. For example, the 'n' modifier includes the 'u' modifier and together they are equivalent to PCRE2_UTF | PCRE2_UCP. When you set a modifier like this, both options get set, and when you remove the 'n' modifier (with RegexMatch::changeModifier()), both will get removed.
Returns
Calculated modifier string (std::string)
See also
Regex::getModifier()
RegexReplace::getModifier()
References jpcre2::ModifierTable::fromMatchOption().
template<typename Char_T , template< typename... > class Map = std::map> virtual ModifierTable const* jpcre2::select< Char_T, Map >::RegexMatch::getModifierTable () [inline], [virtual], [inherited]
Get the modifier table that is set,.
Returns
pointer to constant ModifierTable.
template<typename Char_T , template< typename... > class Map = std::map> virtual VecNas const* jpcre2::select< Char_T, Map >::RegexMatch::getNamedSubstringVector () const [inline], [virtual], [inherited]
Get pointer to named substring vector.
Returns
Pointer to const named substring vector.
template<typename Char_T , template< typename... > class Map = std::map> virtual VecNtN const* jpcre2::select< Char_T, Map >::RegexMatch::getNameToNumberMapVector () const [inline], [virtual], [inherited]
Get pointer to name to number map vector.
Returns
Pointer to const name to number map vector.
template<typename Char_T , template< typename... > class Map = std::map> virtual VecNum const* jpcre2::select< Char_T, Map >::RegexMatch::getNumberedSubstringVector () const [inline], [virtual], [inherited]
Get pointer to numbered substring vector.
Returns
Pointer to const numbered substring vector.
template<typename Char_T , template< typename... > class Map = std::map> virtual Uint jpcre2::select< Char_T, Map >::RegexMatch::getPcre2Option () const [inline], [virtual], [inherited]
Get PCRE2 option.
Returns
PCRE2 option for match operation
See also
Regex::getPcre2Option()
RegexReplace::getPcre2Option()
template<typename Char_T , template< typename... > class Map = std::map> virtual const Regex* jpcre2::select< Char_T, Map >::RegexMatch::getRegexObject () const [inline], [virtual], [inherited]
Get a pointer to the associated Regex object. If no actual Regex object is associated, null is returned.
Returns
A pointer to the associated constant Regex object or null.
template<typename Char_T , template< typename... > class Map = std::map> virtual PCRE2_SIZE jpcre2::select< Char_T, Map >::RegexMatch::getStartOffset () const [inline], [virtual], [inherited]
Get offset from where match will start in the subject.
Returns
Start offset
template<typename Char_T , template< typename... > class Map = std::map> virtual String jpcre2::select< Char_T, Map >::RegexMatch::getSubject () const [inline], [virtual], [inherited]
Get subject string (by value).
Returns
subject string
See also
RegexReplace::getSubject()
template<typename Char_T , template< typename... > class Map = std::map> virtual const String* jpcre2::select< Char_T, Map >::RegexMatch::getSubjectPointer () const [inline], [virtual], [inherited]
Get pointer to subject string. Data can not be changed with this pointer.
Returns
constant subject string pointer
See also
RegexReplace::getSubjectPointer()
template<typename Char_T , template< typename... > class Map = std::map> SIZE_T jpcre2::select< Char_T, Map >::MatchEvaluator::match (void) [inline], [virtual]
Perform match and return the match count. This function strips off matching options (PCRE2_PARTIAL_HARD|PCRE2_PARTIAL_SOFT) that are considered bad options for replacement operation and then calls RegexMatch::match() to perform the match.
Returns
match count.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::changePcre2Option(), and jpcre2::select< Char_T, Map >::RegexMatch::match().
template<typename Char_T , template< typename... > class Map> jpcre2::select< Char_T, Map >::String jpcre2::select< Char_T, Map >::MatchEvaluator::nreplace (bool do_match = true, Uint jro = 0, SIZE_T * counter = 0)
Perform regex replace with this match evaluator. This is a JPCRE2 native replace function (thus the name nreplace). It uses the MatchEvaluatorCallback function that was set with a constructor or MatchEvaluator::setCallback() function to generate the replacement strings on the fly. The string returned by the callback function will be treated as literal and will not go through any further processing.
This function performs a new match everytime it is called unless it is passed with a boolean false as the first argument. To use existing match data that was created by a previous MatchEvaluator::nreplace() or MatchEvaluator::match(), call this function with boolean false as the first argument.
Complexity
1.
Changes in replace related option takes effect without a re-match.
2.
Changes in match related option (e.g start offset) needs a re-match to take effect.
3.
To re-use existing match data, callback function must be compatible with the data, otherwise assertion error.
4.
If the associated Regex object or subject string changes, a new match must be performed, trying to use the existing match data in such cases is undefined behavior.
Parameters
do_match Perform a new matching operation if true, otherwise use existing match data.
jro JPCRE2 replace options.
counter Pointer to a counter to store the number of replacement done.
Returns
resultant string after replace.
See also
MatchEvaluator.
MatchEvaluatorCallback.
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::operator= (MatchEvaluator && me) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Overloaded move-assignment operator. It steals resources from the argument. It leaves the argument in a valid but indeterminate sate. The indeterminate state can be returned to normal by calling reset() on that object.
Parameters
me rvalue reference to a MatchEvaluator object
Returns
A reference to the calling MatchEvaluator object.
See also
MatchEvaluator(MatchEvaluator&& me)
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::operator= (MatchEvaluator const & me) [inline]
Overloaded copy-assignment operator.
Parameters
me MatchEvaluator object
Returns
A reference to the calling MatchEvaluator object.
template<typename Char_T , template< typename... > class Map> jpcre2::select< Char_T, Map >::String jpcre2::select< Char_T, Map >::MatchEvaluator::replace (bool do_match = true, Uint ro = 0, SIZE_T * counter = 0)
PCRE2 compatible replace function that uses this MatchEvaluator. Performs regex replace with pcre2_substitute function by generating the replacement strings dynamically with MatchEvaluator callback. The string returned by callback function is processed by internal pcre2_substitute, thus allowing all options that are provided by PCRE2 itself.
This function performs a new match everytime it is called unless it is passed with a boolean false as the first argument.
Complexity
1.
Changes in replace related option takes effect without a re-match.
2.
Changes in match related option (e.g start offset) needs a re-match to take effect.
3.
To re-use existing match data, callback function must be compatible with the data, otherwise assertion error.
4.
If the associated Regex object or subject string changes, a new match must be performed, trying to use the existing match data in such cases is undefined behavior.
Parameters
do_match perform a new match if true, otherwise use existing data.
ro replace related PCRE2 options.
counter Pointer to a counter to store the number of replacement done.
Returns
resultant string after replacement.
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::reset () [inline], [virtual]
Reset MatchEvaluator to initial state including memory.
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::reset(), and jpcre2::select< Char_T, Map >::MatchEvaluator::resetMatchData().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::resetErrors () [inline], [virtual]
Call RegexMatch::resetErrors().
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::resetErrors().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::resetMatchData () [inline]
Reset match data to initial state. It deletes all match data from all vectors shrinking their capacity. A call to match() or nreplace() will be required to produce match data again.
Returns
A reference to the calling MatchEvaluator object.
Referenced by jpcre2::select< Char_T, Map >::MatchEvaluator::reset().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setBufferSize (PCRE2_SIZE x) [inline]
Set the buffer size that will be used by pcre2_substitute (replace()). If buffer size proves to be enough to fit the resultant string from each match (not the total resultant string), it will yield one less call to pcre2_substitute for each match.
Parameters
x buffer size.
Returns
A reference to the calling MatchEvaluator object.
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback (typename MatchEvaluatorCallback< NumSub const &, MapNas const &, MapNtN const & >::Callback mef) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Sets a callback function with a jp::NumSub, jp::MapNas, jp::MapNtN. You will be working with references of the constant vectors. For maps, you won't be able to use [] operator with reference to constant map, use at() instead:
map_nas["word"]; //wrong
map_nas.at("word"); //ok
If you want to use [] operator with maps, make a copy:
jp::MapNas mn = map_nas;
mn["word"]; //ok
Parameters
mef Callback function.
Returns
A reference to the calling MatchEvaluator object.
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback (typename MatchEvaluatorCallback< NumSub const &, MapNas const &, void * >::Callback mef) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Sets a callback function with a jp::NumSub and jp::MapNas. You will be working with references of the constant vectors. For maps, you won't be able to use [] operator with reference to constant map, use at() instead:
map_nas["word"]; //wrong
map_nas.at("word"); //ok
If you want to use [] operator with maps, make a copy:
jp::MapNas mn = map_nas;
mn["word"]; //ok
Parameters
mef Callback function.
Returns
A reference to the calling MatchEvaluator object.
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback (typename MatchEvaluatorCallback< NumSub const &, void *, MapNtN const & >::Callback mef) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Sets a callback function with a jp::NumSub and jp::MapNtN. You will be working with references of the constant vectors. For maps, you won't be able to use [] operator with reference to constant map, use at() instead:
map_ntn["word"]; //wrong
map_ntn.at("word"); //ok
If you want to use [] operator with maps, make a copy:
jp::MapNtN mn = map_ntn;
mn["word"]; //ok
Parameters
mef Callback function.
Returns
A reference to the calling MatchEvaluator object.
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback (typename MatchEvaluatorCallback< NumSub const &, void *, void * >::Callback mef) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Sets a callback function with a jp::NumSub vector. You will be working with a reference to the constant vector.
Parameters
mef Callback function.
Returns
A reference to the calling MatchEvaluator object.
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback (typename MatchEvaluatorCallback< void *, MapNas const &, MapNtN const & >::Callback mef) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Sets a callback function with a jp::MapNas, jp::MapNtN. You will be working with reference of the constant vector. For maps, you won't be able to use [] operator with reference to constant map, use at() instead:
map_nas["word"]; //wrong
map_nas.at("word"); //ok
If you want to use [] operator with maps, make a copy:
jp::MapNas mn = map_nas;
mn["word"]; //ok
Parameters
mef Callback function.
Returns
A reference to the calling MatchEvaluator object.
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback (typename MatchEvaluatorCallback< void *, MapNas const &, void * >::Callback mef) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Sets a callback function with a jp::MapNas. You will be working with reference of the constant vector. For maps, you won't be able to use [] operator with reference to constant map, use at() instead:
map_nas["word"]; //wrong
map_nas.at("word"); //ok
If you want to use [] operator with maps, make a copy:
jp::MapNas mn = map_nas;
mn["word"]; //ok
Parameters
mef Callback function.
Returns
A reference to the calling MatchEvaluator object.
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback (typename MatchEvaluatorCallback< void *, void *, MapNtN const & >::Callback mef) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... Sets a callback function with a jp::MapNtN. You will be working with references of the constant vectors. For maps, you won't be able to use [] operator with reference to constant map, use at() instead:
map_ntn["word"]; //wrong
map_ntn.at("word"); //ok
If you want to use [] operator with maps, make a copy:
jp::MapNtN mn = map_ntn;
mn["word"]; //ok
Parameters
mef Callback function.
Returns
A reference to the calling MatchEvaluator object.
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setCallback (typename MatchEvaluatorCallback< void *, void *, void * >::Callback mef) [inline]
Member function to set a callback function with no vector reference. Callback function is always overwritten. The implemented vectors are set to be filled with match data. Other vectors that were set previously, are not unset and thus they will be filled with match data too when match() or nreplace() is called.
Parameters
mef Callback function.
Returns
A reference to the calling MatchEvaluator object.
Referenced by jpcre2::select< Char_T, Map >::MatchEvaluator::MatchEvaluator().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setFindAll () [inline], [virtual]
Call RegexMatch::setFindAll().
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::setFindAll().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setFindAll (bool x) [inline], [virtual]
Call RegexMatch::setFindAll(bool x).
Parameters
x true if global match, false otherwise.
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::setFindAll().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setJpcre2Option (Uint x) [inline], [virtual]
Call RegexMatch::setJpcre2Option(Uint x).
Parameters
x JPCRE2 option value.
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::setJpcre2Option().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setMatchContext (MatchContext * match_context) [inline], [virtual]
Call RegexMatch::setMatchContext(MatchContext *match_context).
Parameters
match_context pointer to match context.
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::setMatchContext().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setMatchDataBlock (MatchData * mdt) [inline], [virtual]
Call RegexMatch::setMatchDataBlock(MatchContext * mdt);.
Parameters
mdt pointer to match data block
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::setMatchDataBlock().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setModifier (Modifier const & s) [inline], [virtual]
Call RegexMatch::setModifier(Modifier const& s).
Parameters
s modifier string.
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::setModifier().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setModifierTable (ModifierTable const * mdt) [inline], [virtual]
Call RegexMatch::setModifierTable(ModifierTable const * s).
Parameters
mdt pointer to ModifierTable object.
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::setModifierTable().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setPcre2Option (Uint x) [inline], [virtual]
Call RegexMatch::setPcre2Option (Uint x).
Parameters
x PCRE2 option value.
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::setPcre2Option().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setRegexObject (Regex const * r) [inline], [virtual]
Call RegexMatch::setRegexObject(r).
Parameters
r constant Regex object pointer
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::setRegexObject().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setStartOffset (PCRE2_SIZE offset) [inline], [virtual]
Call RegexMatch::setStartOffset (PCRE2_SIZE offset).
Parameters
offset match start offset in the subject.
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::setStartOffset().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setSubject (String const & s) [inline], [virtual]
Call RegexMatch::setSubject(String const &s).
Parameters
s subject string.
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::setSubject().
template<typename Char_T , template< typename... > class Map = std::map> MatchEvaluator& jpcre2::select< Char_T, Map >::MatchEvaluator::setSubject (String const * s) [inline], [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
s constant subject string by pointer
Returns
A reference to the calling MatchEvaluator object.
Reimplemented from jpcre2::select< Char_T, Map >::RegexMatch.
References jpcre2::select< Char_T, Map >::RegexMatch::setSubject().
Author
Generated automatically by Doxygen for JPCRE2 from the source code.