.TH "jpcre2::ParseInt< Char_T >" 3 "Sat Nov 12 2016" "Version 10.28.05" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::ParseInt< Char_T > \- Contains function that parses integer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jpcre2\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<> std::string \fBtoString\fP (int x)"
.br
.RI "Converts integer to std::string\&. "
.ti -1c
.RI "template<> std::wstring \fBtoString\fP (int x)"
.br
.RI "This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. "
.ti -1c
.RI "template<> std::u16string \fBtoString\fP (int x)"
.br
.RI "This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. "
.ti -1c
.RI "template<> std::u32string \fBtoString\fP (int x)"
.br
.RI "This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Char_T>
.br
struct jpcre2::ParseInt< Char_T >"
Contains function that parses integer\&. 


.SH "Member Function Documentation"
.PP 
.SS "template<> std::string \fBjpcre2::ParseInt\fP< char >::toString (int x)\fC [inline]\fP"

.PP
Converts integer to std::string\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP the integer to convert 
.RE
.PP
\fBReturns:\fP
.RS 4
std::string from the integer 
.RE
.PP

.SS "template<> std::wstring \fBjpcre2::ParseInt\fP< wchar_t >::toString (int x)\fC [inline]\fP"

.PP
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Converts integer to std::wstring 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP the integer to convert 
.RE
.PP
\fBReturns:\fP
.RS 4
std::wstring from the integer 
.RE
.PP

.SS "template<> std::u16string \fBjpcre2::ParseInt\fP< char16_t >::toString (int x)\fC [inline]\fP"

.PP
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Converts integer to std::u16string\&. Uses codecvt to convert to utf16 from utf8 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP int to convert 
.RE
.PP
\fBReturns:\fP
.RS 4
std::u16string from the integer 
.RE
.PP

.SS "template<> std::u32string \fBjpcre2::ParseInt\fP< char32_t >::toString (int x)\fC [inline]\fP"

.PP
This is an overloaded member function, provided for convenience\&. It differs from the above function only in what argument(s) it accepts\&. Converts integer to std::u32string\&. Uses codecvt to convert to utf32 from utf8 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP int to convert 
.RE
.PP
\fBReturns:\fP
.RS 4
std::u32string from the integer 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
