jpcre2::select8< Char_T >
NAME
jpcre2::select8< Char_T > - struct to select 8 bit code unit width and the character type.
SYNOPSIS
Classes
class Regex
Implements public overloaded and copy constructors, provides functions to set/unset various options and perform regex match and replace against a compiled pattern.
class RegexMatch
Provides the RegexMatch::match() function to perform regex matching.
class RegexReplace
Provides the RegexReplace::replace() function to perform regex replace on a string.
Public Types
typedef Char_T Char
Typedef for character (either one of char, wchar_t, char16_t, char32_t that was passed with jpcre2::select8<Char_T>).
typedef std::basic_string< Char_T > String
Typedef for string (either one of std::string, std::wstring, std::u16string, std::u32string).
typedef std::map< String, String > MapNas
Map for Named substrings.
typedef std::map< SIZE_T, String > MapNum
Map for Numbered substrings.
typedef std::map< String, SIZE_T > MapNtN
Substring name to Substring number map.
typedef MapNtN MapNtn
Allow spelling mistake of MapNtN as MapNtn.
typedef std::vector< MapNas > VecNas
Vector of matches with named substrings.
typedef std::vector< MapNtN > VecNtN
Vector of substring name to substring number map.
typedef VecNtN VecNtn
Allow spelling mistake of VecNtN as VecNtn.
typedef std::vector< MapNum > VecNum
Vector of matches with numbered substrings.
Static Public Member Functions
static String toString (int)
Converts an integer to jpcre2::select8<Char_T>::String.
static String toString (Char)
Converts a Char_T to jpcre2::select8<Char_T>::String.
static String toString (const Char *)
Converts an const Char_T* to jpcre2::select8<Char_T>::String.
static String toString (PCRE2_UCHAR *)
Converts a PCRE2_UCHAR* to jpcre2::select8<Char_T>::String.
static String getPcre2ErrorMessage (int)
Return PCRE2 error message by error number.
static String getErrorMessage (int, int)
Return error message according to error number and error offset.
Detailed Description
template<class Char_T>
struct jpcre2::select8< Char_T >"
struct to select 8 bit code unit width and the character type.
If PCRE2_CODE_UNIT_WIDTH 8 is defined you can access it without the suffix (8) i.e jpcre2::select<Char_T>.
Usage: jpcre2::select8<Char_T>.
The character type (Char_T) must be in accordance with the definition of PCRE2_CODE_UNIT_WIDTH. If it doesn't match with the character type, then the behavior is undefined. If the macro JPCRE2_ENABLE_CODE_UNIT_VALIDATION is defined , then such behavior will cause an assertion failure and immediate termination of the program.
Template Parameters:
Char_T Character type (char, wchar_t, char16_t, char32_t).
See also:
jpcre2::select16
jpcre2::select32
Member Typedef Documentation
template<class Char_T> jpcre2::select8< Char_T >::Char
Typedef for character (either one of char, wchar_t, char16_t, char32_t that was passed with jpcre2::select8<Char_T>).
template<class Char_T> jpcre2::select8< Char_T >::MapNas
Map for Named substrings.
template<class Char_T> jpcre2::select8< Char_T >::MapNtN
Substring name to Substring number map.
template<class Char_T> jpcre2::select8< Char_T >::MapNtn
Allow spelling mistake of MapNtN as MapNtn.
template<class Char_T> jpcre2::select8< Char_T >::MapNum
Map for Numbered substrings.
template<class Char_T> jpcre2::select8< Char_T >::String
Typedef for string (either one of std::string, std::wstring, std::u16string, std::u32string). Defined as std::basic_string<Char_T>. May be this list will make more sense: Character String char std::string wchar_t std::wstring char16_t std::u16string (>=C++11) char32_t std::u32string (>=C++11)
template<class Char_T> jpcre2::select8< Char_T >::VecNas
Vector of matches with named substrings.
template<class Char_T> jpcre2::select8< Char_T >::VecNtN
Vector of substring name to substring number map.
template<class Char_T> jpcre2::select8< Char_T >::VecNtn
Allow spelling mistake of VecNtN as VecNtn.
template<class Char_T> jpcre2::select8< Char_T >::VecNum
Vector of matches with numbered substrings.
Member Function Documentation
template<class Char_T > jpcre2::select8< Char_T >::getErrorMessage (int err_num, int err_off) [static]
Return error message according to error number and error offset.
Template Parameters:
Char_T Character type
Parameters:
err_num Error number
err_off Error offset
Returns:
Error message as a string (jpcre2::select8<Char_T>::String)
References jpcre2::ERROR::JIT_COMPILE_FAILED.
template<class Char_T > jpcre2::select8< Char_T >::getPcre2ErrorMessage (int err_num) [static]
Return PCRE2 error message by error number.
Template Parameters:
Char_T Character type
Parameters:
err_num PCRE2 error number
Returns:
Error message as jpcre2::select8<Char_T>::String
template<class Char_T > jpcre2::select8< Char_T >::String jpcre2::select8< Char_T >::toString (int x) [static]
Converts an integer to jpcre2::select8<Char_T>::String.
Template Parameters:
Char_T Character type
Parameters:
x Integer to be converted
Returns:
jpcre2::select8<Char_T>::String
Referenced by jpcre2::select8< Char_T >::RegexMatch::changeModifier(), jpcre2::select8< Char_T >::RegexReplace::replace(), and jpcre2::select8< Char_T >::toString().
template<class Char_T > jpcre2::select8< Char_T >::toString (const Char * a) [static]
Converts an const Char_T* to jpcre2::select8<Char_T>::String.
Template Parameters:
Char_T Character type
Parameters:
a Character pointer
Returns:
jpcre2::select8<Char_T>::String
References jpcre2::select8< Char_T >::toString().
template<class Char_T > jpcre2::select8< Char_T >::toString (PCRE2_UCHAR * a) [static]
Converts a PCRE2_UCHAR* to jpcre2::select8<Char_T>::String.
Template Parameters:
Char_T Character type
Parameters:
a PCRE2_UCHAR pointer
Returns:
jpcre2::select8<Char_T>::String
References jpcre2::select8< Char_T >::toString().
template<class Char_T > jpcre2::select8< Char_T >::toString (Char a) [static]
Converts a Char_T to jpcre2::select8<Char_T>::String.
Template Parameters:
Char_T Character type
Parameters:
a Character to be converted
Returns:
jpcre2::select8<Char_T>::String
References jpcre2::select8< Char_T >::toString().
Author
Generated automatically by Doxygen for JPCRE2 from the source code.