jpcre2::ModifierTable
NAME
jpcre2::ModifierTable - Lets you create custom modifier tables.
SYNOPSIS
#include <jpcre2.hpp>
Public Member Functions
ModifierTable ()
Default constructor that creates an empty modifier table.
ModifierTable (bool deflt)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
ModifierTable & resetMatchModifierTable ()
Reset the match modifier table to its initial (empty) state including memory.
ModifierTable & resetReplaceModifierTable ()
Reset the replace modifier table to its initial (empty) state including memory.
ModifierTable & resetCompileModifierTable ()
Reset the compile modifier table to its initial (empty) state including memory.
ModifierTable & reset ()
Reset the modifier tables to their initial (empty) state including memory.
ModifierTable & clearMatchModifierTable ()
Clear the match modifier table to its initial (empty) state.
ModifierTable & clearReplaceModifierTable ()
Clear the replace modifier table to its initial (empty) state.
ModifierTable & clearCompileModifierTable ()
Clear the compile modifier table to its initial (empty) state.
ModifierTable & clear ()
Clear the modifier tables to their initial (empty) state.
void toMatchOption (Modifier const &mod, bool x, Uint *po, Uint *jo, int *en, SIZE_T *eo) const
Modifier parser for match related options.
void toReplaceOption (Modifier const &mod, bool x, Uint *po, Uint *jo, int *en, SIZE_T *eo) const
Modifier parser for replace related options.
void toCompileOption (Modifier const &mod, bool x, Uint *po, Uint *jo, int *en, SIZE_T *eo) const
Modifier parser for compile related options.
std::string fromMatchOption (Uint po, Uint jo) const
Take match related option value and convert to modifier string.
std::string fromReplaceOption (Uint po, Uint jo) const
Take replace related option value and convert to modifier string.
std::string fromCompileOption (Uint po, Uint jo) const
Take compile related option value and convert to modifier string.
ModifierTable & setMatchModifierTable (std::string const &tabs, VecOpt const &tabv)
Set modifier table for match.
ModifierTable & setMatchModifierTable (std::string const &tabs, const Uint *tabvp)
Set modifier table for match.
ModifierTable & setMatchModifierTable (const char *tabsp, const Uint *tabvp)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
ModifierTable & setReplaceModifierTable (std::string const &tabs, VecOpt const &tabv)
Set modifier table for replace.
ModifierTable & setReplaceModifierTable (std::string const &tabs, const Uint *tabvp)
Set modifier table for replace.
ModifierTable & setReplaceModifierTable (const char *tabsp, const Uint *tabvp)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
ModifierTable & setCompileModifierTable (std::string const &tabs, VecOpt const &tabv)
Set modifier table for compile.
ModifierTable & setCompileModifierTable (std::string const &tabs, const Uint *tabvp)
Set modifier table for compile.
ModifierTable & setCompileModifierTable (const char *tabsp, const Uint *tabvp)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ...
ModifierTable & setMatchModifierTableToDefault ()
Set match modifie table to default.
ModifierTable & setReplaceModifierTableToDefault ()
Set replace modifier table to default.
ModifierTable & setCompileModifierTableToDefault ()
Set compile modifier table to default.
ModifierTable & setAllToDefault ()
Set all tables to default.
Detailed Description
Lets you create custom modifier tables.
An instance of this class can be passed to match, replace or compile related class objects.
Constructor & Destructor Documentation
jpcre2::ModifierTable::ModifierTable () [inline]
Default constructor that creates an empty modifier table.
jpcre2::ModifierTable::ModifierTable (bool deflt) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters:
deflt Initialize with default table if true, otherwise keep empty.
Member Function Documentation
ModifierTable& jpcre2::ModifierTable::clear () [inline]
Clear the modifier tables to their initial (empty) state. Memory may retain for further use.
Returns:
A reference to the calling ModifierTable object.
Referenced by clearCompileModifierTable(), clearMatchModifierTable(), and clearReplaceModifierTable().
ModifierTable& jpcre2::ModifierTable::clearCompileModifierTable () [inline]
Clear the compile modifier table to its initial (empty) state. Memory may retain for further use.
Returns:
A reference to the calling ModifierTable object.
References clear().
ModifierTable& jpcre2::ModifierTable::clearMatchModifierTable () [inline]
Clear the match modifier table to its initial (empty) state. Memory may retain for further use.
Returns:
A reference to the calling ModifierTable object.
References clear().
ModifierTable& jpcre2::ModifierTable::clearReplaceModifierTable () [inline]
Clear the replace modifier table to its initial (empty) state. Memory may retain for further use.
Returns:
A reference to the calling ModifierTable object.
References clear().
std::string jpcre2::ModifierTable::fromCompileOption (Uint po, Uint jo) const [inline]
Take compile related option value and convert to modifier string.
Parameters:
po PCRE2 option.
jo JPCRE2 option.
Returns:
modifier string (std::string)
Referenced by jpcre2::select< Char_T, Map >::Regex::getModifier().
std::string jpcre2::ModifierTable::fromMatchOption (Uint po, Uint jo) const [inline]
Take match related option value and convert to modifier string.
Parameters:
po PCRE2 option.
jo JPCRE2 option.
Returns:
modifier string (std::string)
Referenced by jpcre2::select< Char_T, Map >::RegexMatch::getModifier().
std::string jpcre2::ModifierTable::fromReplaceOption (Uint po, Uint jo) const [inline]
Take replace related option value and convert to modifier string.
Parameters:
po PCRE2 option.
jo JPCRE2 option.
Returns:
modifier string (std::string)
Referenced by jpcre2::select< Char_T, Map >::RegexReplace::getModifier().
ModifierTable& jpcre2::ModifierTable::reset () [inline]
Reset the modifier tables to their initial (empty) state including memory.
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::resetCompileModifierTable () [inline]
Reset the compile modifier table to its initial (empty) state including memory.
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::resetMatchModifierTable () [inline]
Reset the match modifier table to its initial (empty) state including memory.
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::resetReplaceModifierTable () [inline]
Reset the replace modifier table to its initial (empty) state including memory.
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::setAllToDefault () [inline]
Set all tables to default.
Returns:
A reference to the calling ModifierTable object.
References jpcre2::ERROR::INSUFFICIENT_OVECTOR, and jpcre2::ERROR::INVALID_MODIFIER.
ModifierTable& jpcre2::ModifierTable::setCompileModifierTable (std::string const & tabs, VecOpt const & tabv) [inline]
Set modifier table for compile. Takes a string and a vector of sequential options.
Parameters:
tabs modifier string (list of modifiers)
tabv vector of Uint (options).
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::setCompileModifierTable (std::string const & tabs, const Uint * tabvp) [inline]
Set modifier table for compile. Takes a string and an array of sequential options.
Parameters:
tabs modifier string (list of modifiers)
tabvp array of Uint (options). If null, table is set to empty.
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::setCompileModifierTable (const char * tabsp, const Uint * tabvp) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... This one takes modifier and value by array. If the arrays are not of the same length, the behavior is undefined. If any of the argument is null, the table is set empty.
Parameters:
tabsp modifier string (list of modifiers).
tabvp array of Uint (options).
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::setCompileModifierTableToDefault () [inline]
Set compile modifier table to default.
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::setMatchModifierTable (std::string const & tabs, VecOpt const & tabv) [inline]
Set modifier table for match. Takes a string and a vector of sequential options.
Parameters:
tabs modifier string (list of modifiers)
tabv vector of Uint (options).
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::setMatchModifierTable (std::string const & tabs, const Uint * tabvp) [inline]
Set modifier table for match. Takes a string and an array of sequential options.
Parameters:
tabs modifier string (list of modifiers)
tabvp array of Uint (options). If null, table is set to empty.
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::setMatchModifierTable (const char * tabsp, const Uint * tabvp) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... This one takes modifier and value by array. If the arrays are not of the same length, the behavior is undefined. If any of the argument is null, the table is set empty.
Parameters:
tabsp modifier string (list of modifiers).
tabvp array of Uint (options).
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::setMatchModifierTableToDefault () [inline]
Set match modifie table to default.
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::setReplaceModifierTable (std::string const & tabs, VecOpt const & tabv) [inline]
Set modifier table for replace. Takes a string and a vector of sequential options.
Parameters:
tabs modifier string (list of modifiers)
tabv vector of Uint (options).
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::setReplaceModifierTable (std::string const & tabs, const Uint * tabvp) [inline]
Set modifier table for replace. Takes a string and an array of sequential options.
Parameters:
tabs modifier string (list of modifiers)
tabvp array of Uint (options). If null, table is set to empty.
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::setReplaceModifierTable (const char * tabsp, const Uint * tabvp) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. ... This one takes modifier and value by array. If the arrays are not of the same length, the behavior is undefined. If any of the argument is null, the table is set empty.
Parameters:
tabsp modifier string (list of modifiers).
tabvp array of Uint (options).
Returns:
A reference to the calling ModifierTable object.
ModifierTable& jpcre2::ModifierTable::setReplaceModifierTableToDefault () [inline]
Set replace modifier table to default.
Returns:
A reference to the calling ModifierTable object.
void jpcre2::ModifierTable::toCompileOption (Modifier const & mod, bool x, Uint * po, Uint * jo, int * en, SIZE_T * eo) const [inline]
Modifier parser for compile related options.
Parameters:
mod modifier string
x whether to add or remove the modifers.
po pointer to PCRE2 compile option that will be modified.
jo pointer to JPCRE2 compile option that will be modified.
en where to put the error number.
eo where to put the error offset.
Referenced by jpcre2::select< Char_T, Map >::Regex::changeModifier().
void jpcre2::ModifierTable::toMatchOption (Modifier const & mod, bool x, Uint * po, Uint * jo, int * en, SIZE_T * eo) const [inline]
Modifier parser for match related options.
Parameters:
mod modifier string
x whether to add or remove the modifers.
po pointer to PCRE2 match option that will be modified.
jo pointer to JPCRE2 match option that will be modified.
en where to put the error number.
eo where to put the error offset.
Referenced by jpcre2::select< Char_T, Map >::RegexMatch::changeModifier().
void jpcre2::ModifierTable::toReplaceOption (Modifier const & mod, bool x, Uint * po, Uint * jo, int * en, SIZE_T * eo) const [inline]
Modifier parser for replace related options.
Parameters:
mod modifier string
x whether to add or remove the modifers.
po pointer to PCRE2 replace option that will be modified.
jo pointer to JPCRE2 replace option that will be modified.
en where to put the error number.
eo where to put the error offset.
Referenced by jpcre2::select< Char_T, Map >::RegexReplace::changeModifier().
Author
Generated automatically by Doxygen for JPCRE2 from the source code.