.TH "jpcre2::MOD" 3 "Wed Oct 26 2016" "Version 10.27.03" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::MOD \- Namespace for modifier constants\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const std::string \fBC_N\fP ('eijmnsuxADJU')"
.br
.RI "String of compile modifier characters for PCRE2 options\&. "
.ti -1c
.RI "const std::string \fBCJ_N\fP ('S')"
.br
.RI "String of compile modifier characters for JPCRE2 options\&. "
.ti -1c
.RI "const std::string \fBR_N\fP ('eEgx')"
.br
.RI "String of action (replace) modifier characters for PCRE2 options\&. "
.ti -1c
.RI "const std::string \fBRJ_N\fP ('')"
.br
.RI "String of action (replace) modifier characters for JPCRE2 options\&. "
.ti -1c
.RI "const std::string \fBM_N\fP ('A')"
.br
.RI "String of action (match) modifier characters for PCRE2 options\&. "
.ti -1c
.RI "const std::string \fBMJ_N\fP ('g')"
.br
.RI "String of action (match) modifier characters for JPCRE2 options\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBjpcre2::Uint\fP \fBC_V\fP [12]"
.br
.RI "Array of compile modifier values for PCRE2 options\&. "
.ti -1c
.RI "const \fBjpcre2::Uint\fP \fBCJ_V\fP [1]"
.br
.RI "Array of compile modifier values for JPCRE2 options\&. "
.ti -1c
.RI "const \fBjpcre2::Uint\fP \fBR_V\fP [4]"
.br
.RI "Array of action (replace) modifier values for PCRE2 options\&. "
.ti -1c
.RI "const \fBjpcre2::Uint\fP \fBRJ_V\fP [1]"
.br
.RI "Array of action (replace) modifier values for JPCRE2 options\&. "
.ti -1c
.RI "const \fBjpcre2::Uint\fP \fBM_V\fP [1]"
.br
.RI "Array of action (match) modifier values for PCRE2 options\&. "
.ti -1c
.RI "const \fBjpcre2::Uint\fP \fBMJ_V\fP [1]"
.br
.RI "Array of action (match) modifier values for JPCRE2 options\&. "
.in -1c
.SH "Detailed Description"
.PP 
Namespace for modifier constants\&. 

For each modifier constant there is a \fBjpcre2::Uint\fP option value\&. Some modifiers may have multiple values set together (ORed in bitwise operation) and thus they may include other modifiers\&. Such an example is the 'n' modifier\&. It is combined together with 'u'\&. 
.SH "Function Documentation"
.PP 
.SS "const std::string jpcre2::MOD::C_N ('eijmnsuxADJU')"

.PP
String of compile modifier characters for PCRE2 options\&. 
.SS "const std::string jpcre2::MOD::CJ_N ('S')"

.PP
String of compile modifier characters for JPCRE2 options\&. 
.SS "const std::string jpcre2::MOD::M_N ('A')"

.PP
String of action (match) modifier characters for PCRE2 options\&. 
.SS "const std::string jpcre2::MOD::MJ_N ('g')"

.PP
String of action (match) modifier characters for JPCRE2 options\&. 
.SS "const std::string jpcre2::MOD::R_N ('eEgx')"

.PP
String of action (replace) modifier characters for PCRE2 options\&. 
.SS "const std::string jpcre2::MOD::RJ_N ('')"

.PP
String of action (replace) modifier characters for JPCRE2 options\&. 
.SH "Variable Documentation"
.PP 
.SS "const \fBjpcre2::Uint\fP jpcre2::MOD::C_V[12]"
\fBInitial value:\fP
.PP
.nf
= { PCRE2_MATCH_UNSET_BACKREF,                  
                                                PCRE2_CASELESS,                             
                                                PCRE2_ALT_BSUX | PCRE2_MATCH_UNSET_BACKREF, 
                                                PCRE2_MULTILINE,                            
                                                PCRE2_UTF | PCRE2_UCP,                      
                                                PCRE2_DOTALL,                               
                                                PCRE2_UTF,                                  
                                                PCRE2_EXTENDED,                             
                                                PCRE2_ANCHORED,                             
                                                PCRE2_DOLLAR_ENDONLY,                       
                                                PCRE2_DUPNAMES,                             
                                                PCRE2_UNGREEDY                              
                                              }
.fi
.PP
Array of compile modifier values for PCRE2 options\&. 
.SS "const \fBjpcre2::Uint\fP jpcre2::MOD::CJ_V[1]"
\fBInitial value:\fP
.PP
.nf
= { JIT_COMPILE,                                
                                              }
.fi
.PP
Array of compile modifier values for JPCRE2 options\&. 
.SS "const \fBjpcre2::Uint\fP jpcre2::MOD::M_V[1]"
\fBInitial value:\fP
.PP
.nf
= { PCRE2_ANCHORED                               
                                             }
.fi
.PP
Array of action (match) modifier values for PCRE2 options\&. 
.SS "const \fBjpcre2::Uint\fP jpcre2::MOD::MJ_V[1]"
\fBInitial value:\fP
.PP
.nf
= { FIND_ALL,                                   
                                              }
.fi
.PP
Array of action (match) modifier values for JPCRE2 options\&. 
.SS "const \fBjpcre2::Uint\fP jpcre2::MOD::R_V[4]"
\fBInitial value:\fP
.PP
.nf
= { PCRE2_SUBSTITUTE_UNSET_EMPTY,                
                                               PCRE2_SUBSTITUTE_UNKNOWN_UNSET | PCRE2_SUBSTITUTE_UNSET_EMPTY,   
                                               PCRE2_SUBSTITUTE_GLOBAL,                     
                                               PCRE2_SUBSTITUTE_EXTENDED                    
                                             }
.fi
.PP
Array of action (replace) modifier values for PCRE2 options\&. 
.SS "const \fBjpcre2::Uint\fP jpcre2::MOD::RJ_V[1]"
\fBInitial value:\fP
.PP
.nf
= { NONE
                                              }
.fi
.PP
Array of action (replace) modifier values for JPCRE2 options\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
