.TH "jpcre2::ConvUTF< Char_T >" 3 "Sun Jan 22 2017" "Version 10.28.12" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::ConvUTF< Char_T > \- \fCUTF-8 <> UTF-16\fP and \fCUTF-8 <> UTF32\fP converter (\fC>=C++11\fP)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jpcre2\&.hpp>\fP
.SH "Detailed Description"
.PP 

.SS "template<typename Char_T>
.br
struct jpcre2::ConvUTF< Char_T >"
\fCUTF-8 <> UTF-16\fP and \fCUTF-8 <> UTF32\fP converter (\fC>=C++11\fP)\&. 

Convert \fCUTF-16 <> UTF-8\fP: 
.PP
.nf
ConvUTF<char16_t>::Converter conv;
//UTF-16 to UTF-8
std::string s = conv\&.to_bytes(utf16string);
//UTF-8 to UTF-16
std::u16string us = conv\&.from_bytes(utf8string);

.fi
.PP
 Convert \fCUTF-8 <> UTF-16\fP: 
.PP
.nf
ConvUTF<char32_t>::Converter conv;
//UTF-8 to UTF-32
std::u16string us = conv\&.from_bytes(utf8string);
//UTF-32 to UTF-8
std::string s = conv\&.to_bytes(utf32string);

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
