.TH "jpcre2.hpp" 3 "Tue Nov 15 2016" "Version 10.28.06" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2.hpp \- Main header file for JPCRE2 library to be included by programs that uses its functionalities\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <pcre2\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cwchar>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <clocale>\fP
.br
\fC#include <climits>\fP
.br
\fC#include <codecvt>\fP
.br
\fC#include <locale>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBjpcre2::Codecvt< internT, externT, stateT >\fP"
.br
.RI "Convenience wrapper of \fCstd::codecvt\fP\&. "
.ti -1c
.RI "struct \fBjpcre2::ParseInt< Char_T >\fP"
.br
.RI "Contains function that parses integer\&. "
.ti -1c
.RI "struct \fBjpcre2::select< Char_T, BS >\fP"
.br
.RI "struct to select code unit width and the character type\&. "
.ti -1c
.RI "class \fBjpcre2::select< Char_T, BS >::RegexMatch\fP"
.br
.RI "Provides public constructors to create \fBRegexMatch\fP objects\&. "
.ti -1c
.RI "class \fBjpcre2::select< Char_T, BS >::RegexReplace\fP"
.br
.RI "Provides public constructors to create \fBRegexReplace\fP objects\&. "
.ti -1c
.RI "class \fBjpcre2::select< Char_T, BS >::Regex\fP"
.br
.RI "Provides public constructos to create \fBRegex\fP object\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjpcre2\fP"
.br
.RI "Top level namespace of JPCRE2\&. "
.ti -1c
.RI " \fBjpcre2::INFO\fP"
.br
.RI "Namespace to provide information about JPCRE2 library itself\&. "
.ti -1c
.RI " \fBjpcre2::ERROR\fP"
.br
.RI "Namespace for error codes\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPCRE2_CODE_UNIT_WIDTH\fP   0"
.br
.RI "This macro does not have any significance in JPCRE2 context\&. "
.ti -1c
.RI "#define \fBJPCRE2_DISABLE_CODE_UNIT_WIDTH_VALIDATION\fP"
.br
.RI "By default JPCRE2 checks if the code unit width equals to sizeof(Char_T)*CHAR_BIT, if not,it will produce compile error\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef PCRE2_SIZE \fBjpcre2::SIZE_T\fP"
.br
.RI "Used for match count and vector size\&. "
.ti -1c
.RI "typedef uint32_t \fBjpcre2::Uint\fP"
.br
.RI "Used for options (bitwise operation) "
.ti -1c
.RI "typedef uint8_t \fBjpcre2::Ush\fP"
.br
.RI "8 bit unsigned integer\&. "
.ti -1c
.RI "typedef std::wstring_convert< Codecvt< char16_t, char, std::mbstate_t >, char16_t > \fBjpcre2::Convert16\fP"
.br
.RI "This is a convenience typedef (>=C++11) to convert between UTF-8 <> UTF-16\&. "
.ti -1c
.RI "typedef std::wstring_convert< Codecvt< char32_t, char, std::mbstate_t >, char32_t > \fBjpcre2::Convert32\fP"
.br
.RI "This is a convenience typedef (>=C++11) to convert between UTF-8 <> UTF-32\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBjpcre2::ERROR::INVALID_MODIFIER\fP = 2 }
.RI "Error numbers for JPCRE2\&. ""
.br
.ti -1c
.RI "enum { \fBjpcre2::NONE\fP = 0x0000000u, \fBjpcre2::FIND_ALL\fP = 0x0000002u, \fBjpcre2::JIT_COMPILE\fP = 0x0000004u }
.RI "These constants provide JPCRE2 options\&. ""
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const char \fBjpcre2::INFO::NAME\fP [] = 'JPCRE2'"
.br
.RI "Name of the project\&. "
.ti -1c
.RI "static const char \fBjpcre2::INFO::FULL_VERSION\fP [] = '10\&.28\&.06'"
.br
.RI "Full version string\&. "
.ti -1c
.RI "static const char \fBjpcre2::INFO::VERSION_GENRE\fP [] = '10'"
.br
.RI "Generation, depends on original PCRE2 version\&. "
.ti -1c
.RI "static const char \fBjpcre2::INFO::VERSION_MAJOR\fP [] = '28'"
.br
.RI "Major version, updated when API change is made\&. "
.ti -1c
.RI "static const char \fBjpcre2::INFO::VERSION_MINOR\fP [] = '06'"
.br
.RI "Minor version, includes bug fix or minor feature upgrade\&. "
.ti -1c
.RI "static const char \fBjpcre2::INFO::VERSION_PRE_RELEASE\fP [] = ''"
.br
.RI "Alpha or beta (testing) release version\&. "
.ti -1c
.RI "static const SIZE_T \fBjpcre2::SUBSTITUTE_RESULT_INIT_SIZE\fP = 0"
.br
.RI "Used by default to provide big enough initial buffer for replaced string\&. "
.in -1c
.SH "Detailed Description"
.PP 
Main header file for JPCRE2 library to be included by programs that uses its functionalities\&. 

It includes the pcre2\&.h header, therefore you shouldn't include pcre2\&.h separately in your program\&. Make sure to link PCRE2 library when compiling\&. 
.PP
\fBAuthor:\fP
.RS 4
\fCMd Jahidul Hamid\fP 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define JPCRE2_DISABLE_CODE_UNIT_WIDTH_VALIDATION"

.PP
By default JPCRE2 checks if the code unit width equals to sizeof(Char_T)*CHAR_BIT, if not,it will produce compile error\&. This check can be disabled by defining this macro\&. 
.SS "#define PCRE2_CODE_UNIT_WIDTH   0"

.PP
This macro does not have any significance in JPCRE2 context\&. It is defined as 0 by default\&. Defining it before including \fBjpcre2\&.hpp\fP will override the default (0), but still it will have no effect in a JPCRE2 perspective\&. Defining it with an invalid value will yield to compile error\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
