.TH "jpcre2::select" 3 "Wed Oct 26 2016" "Version 10.27.03" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::select \- struct to select the character type and PCRE2_CODE_UNIT_WIDTH as the code unit width\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
struct to select the character type and PCRE2_CODE_UNIT_WIDTH as the code unit width\&. 

If you define PCRE2_CODE_UNIT_WIDTH to be 8, 16 or 32, the templated struct \fBjpcre2::select\fP will inherit one of the original struct from \fBjpcre2::select8\fP, \fBjpcre2::select16\fP or \fBjpcre2::select32\fP respectively and have complete access to the public API\&.
.PP
Implementation of \fBjpcre2::select8\fP, \fBjpcre2::select16\fP or \fBjpcre2::select32\fP are the same with same types of members, typdefs etc \&.\&.\&.
.PP
Usage: \fC\fBjpcre2::select\fP<Char_T>\fP\&.
.PP
The character type (\fCChar_T\fP) must be in accordance with the definition of PCRE2_CODE_UNIT_WIDTH\&. If it doesn't match with the character type, then the behavior is undefined\&. If the macro \fCJPCRE2_ENABLE_CODE_UNIT_VALIDATION\fP is defined , then such behavior will cause an assertion failure and immediate termination of the program\&.
.PP
When working with a single code unit width, \fBjpcre2::select\fP can be used in place of \fBjpcre2::select8\fP for 8bit, or in place of \fBjpcre2::select16\fP for 16bit, or in place of \fBjpcre2::select32\fP for 32bit\&.
.PP
When working with multiple code unit width, \fBjpcre2::select\fP family of strcuts must be called with their original names\&. 
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIChar_T\fP Character type (\fCchar\fP, \fCwchar_t\fP, \fCchar16_t\fP, \fCchar32_t\fP)\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBjpcre2::select8\fP 
.PP
\fBjpcre2::select16\fP 
.PP
\fBjpcre2::select32\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
