.TH "jpcre2::Codecvt< internT, externT, stateT >" 3 "Wed Nov 16 2016" "Version 10.28.07" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::Codecvt< internT, externT, stateT > \- Convenience wrapper of std::codecvt (\fC>=C++11\fP)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jpcre2\&.hpp>\fP
.SH "Detailed Description"
.PP 

.SS "template<class internT, class externT, class stateT>
.br
struct jpcre2::Codecvt< internT, externT, stateT >"
Convenience wrapper of std::codecvt (\fC>=C++11\fP) 

.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
