.TH "jpcre2::INFO" 3 "Thu Nov 10 2016" "Version 10.28.04" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpcre2::INFO \- Namespace to provide information about JPCRE2 library itself\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBNAME\fP = 'JPCRE2'"
.br
.RI "Name of the project\&. "
.ti -1c
.RI "const std::string \fBFULL_VERSION\fP = '10\&.28\&.04'"
.br
.RI "Full version string\&. "
.ti -1c
.RI "const std::string \fBVERSION_GENRE\fP = '10'"
.br
.RI "Generation, depends on original PCRE2 version\&. "
.ti -1c
.RI "const std::string \fBVERSION_MAJOR\fP = '28'"
.br
.RI "Major version, updated when API change is made\&. "
.ti -1c
.RI "const std::string \fBVERSION_MINOR\fP = '04'"
.br
.RI "Minor version, includes bug fix or minor feature upgrade\&. "
.ti -1c
.RI "const std::string \fBVERSION_PRE_RELEASE\fP = ''"
.br
.RI "Alpha or beta (testing) release version\&. "
.in -1c
.SH "Detailed Description"
.PP 
Namespace to provide information about JPCRE2 library itself\&. 

Contains constant Strings with version info\&. 
.SH "Variable Documentation"
.PP 
.SS "const std::string jpcre2::INFO::FULL_VERSION = '10\&.28\&.04'"

.PP
Full version string\&. 
.SS "const std::string jpcre2::INFO::NAME = 'JPCRE2'"

.PP
Name of the project\&. 
.SS "const std::string jpcre2::INFO::VERSION_GENRE = '10'"

.PP
Generation, depends on original PCRE2 version\&. 
.SS "const std::string jpcre2::INFO::VERSION_MAJOR = '28'"

.PP
Major version, updated when API change is made\&. 
.SS "const std::string jpcre2::INFO::VERSION_MINOR = '04'"

.PP
Minor version, includes bug fix or minor feature upgrade\&. 
.SS "const std::string jpcre2::INFO::VERSION_PRE_RELEASE = ''"

.PP
Alpha or beta (testing) release version\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
