.TH "testcov.cpp" 3 "Mon Mar 6 2017" "Version 10.29.03" "JPCRE2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testcov.cpp \- Simulating and discussing various erroneous situations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'jpcre2\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Simulating and discussing various erroneous situations\&. 

This program will always exit with non-zero exit status\&.
.PP
.PP
.nf
.fi
.PP
 
.PP
\fBAuthor:\fP
.RS 4
\fCMd Jahidul Hamid\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for JPCRE2 from the source code\&.
